using System.Linq;
using Content.Client._Utopia.SpeechBarks;
using Content.Client.Stylesheets;
using Content.Shared._Utopia.SpeechBarks;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Utopia.Barks;

[GenerateTypedNameReferences]
public sealed partial class BarkTab : Control
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly ILocalizationManager _loc = default!;

    private readonly SpeechBarksSystem _barkSystem;

    private List<BarkPrototype> _allBarks = new();
    private List<BarkPrototype> _filteredBarks = new();
    private Dictionary<string, List<BarkPrototype>> _barksByCategory = new();

    private string? _selectedCategory = null;
    private string _currentBarkId = default!;
    private float _currentPitch = 1f;
    private float _currentMinVar = 0.1f;
    private float _currentMaxVar = 0.5f;

    public event Action<string>? OnBarkSelected;
    public event Action<float>? OnPitchChanged;
    public event Action<float>? OnMinVarChanged;
    public event Action<float>? OnMaxVarChanged;

    public BarkTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _barkSystem = IoCManager.Resolve<IEntityManager>().System<SpeechBarksSystem>();

        SearchEdit.OnTextChanged += OnSearchTextChanged;
        PitchEdit.OnTextChanged += OnPitchTextChanged;
        DelayVariationMinEdit.OnTextChanged += OnMinVarTextChanged;
        DelayVariationMaxEdit.OnTextChanged += OnMaxVarTextChanged;

        LoadBarks();
    }

    public void SetSelectedBark(string barkId, float pitch, float minVar, float maxVar)
    {
        _currentBarkId = barkId;
        _currentPitch = pitch;
        _currentMinVar = minVar;
        _currentMaxVar = maxVar;

        PitchEdit.Text = pitch.ToString("F2");
        DelayVariationMinEdit.Text = minVar.ToString("F2");
        DelayVariationMaxEdit.Text = maxVar.ToString("F2");

        UpdateBarkButtons();
    }

    private void LoadBarks()
    {
        _allBarks = _prototypeManager
            .EnumeratePrototypes<BarkPrototype>()
            .Where(b => b.RoundStart)
            .OrderBy(b => Loc.GetString(b.Name))
            .ToList();

        _barksByCategory = _allBarks
            .GroupBy(b => b.Category)
            .ToDictionary(g => g.Key, g => g.ToList());

        BuildCategoryButtons();
        FilterBarks();
    }

    private void BuildCategoryButtons()
    {
        CategoriesContainer.RemoveAllChildren();
        var allButton = new Button
        {
            Text = Loc.GetString($"bark-category-all"),
            ToggleMode = true,
            StyleClasses = { StyleClass.ButtonOpenRight },
            HorizontalExpand = true,
            HorizontalAlignment = HAlignment.Left,
            MinWidth = 180,
            MaxWidth = 180,
        };

        allButton.OnPressed += _ => SelectCategory(null);
        CategoriesContainer.AddChild(allButton);
        foreach (var category in _barksByCategory.Keys.OrderBy(c => c))
        {
            var localizedCategory = _loc.TryGetString($"bark-category-{category}", out var localized)
                ? localized
                : category;

            var button = new Button
            {
                Text = localizedCategory,
                ToggleMode = true,
                StyleClasses = { StyleClass.ButtonOpenRight },
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Left,
                MinWidth = 180,
                MaxWidth = 180,
            };

            button.OnPressed += _ => SelectCategory(category);
            CategoriesContainer.AddChild(button);
        }
    }

    private void SelectCategory(string? category)
    {
        _selectedCategory = category;
        var displayName = category == null
            ? Loc.GetString($"bark-category-all")
            : (_loc.TryGetString($"bark-category-{category}", out var localized) ? localized : category);

        var buttons = CategoriesContainer.Children.OfType<Button>().ToList();
        foreach (var button in buttons)
        {
            if (category == null && button.Text == _loc.GetString($"bark-category-all"))
            {
                button.Pressed = true;
            }
            else
            {
                var buttonCategory = category != null && _loc.TryGetString($"bark-category-{category}", out var loc) ? loc : category;
                button.Pressed = button.Text == buttonCategory;
            }
        }

        SelectedCategoryLabel.Text = displayName;
        FilterBarks();
    }

    private void OnSearchTextChanged(LineEdit.LineEditEventArgs args)
    {
        FilterBarks();
    }

    private void OnPitchTextChanged(LineEdit.LineEditEventArgs args)
    {
        if (float.TryParse(args.Text, out var pitch))
        {
            _currentPitch = pitch;
            OnPitchChanged?.Invoke(pitch);
        }
    }

    private void OnMinVarTextChanged(LineEdit.LineEditEventArgs args)
    {
        if (float.TryParse(args.Text, out var minVar))
        {
            _currentMinVar = minVar;
            OnMinVarChanged?.Invoke(minVar);
        }
    }

    private void OnMaxVarTextChanged(LineEdit.LineEditEventArgs args)
    {
        if (float.TryParse(args.Text, out var maxVar))
        {
            _currentMaxVar = maxVar;
            OnMaxVarChanged?.Invoke(maxVar);
        }
    }

    private void FilterBarks()
    {
        var searchText = SearchEdit.Text.ToLower();
        IEnumerable<BarkPrototype> barks;
        if (_selectedCategory != null)
        {
            barks = _barksByCategory.GetValueOrDefault(_selectedCategory, new List<BarkPrototype>());
        }
        else
        {
            barks = _allBarks;
        }

        if (!string.IsNullOrWhiteSpace(searchText))
        {
            barks = barks.Where(b =>
                Loc.GetString(b.Name).ToLower().Contains(searchText) ||
                b.ID.ToLower().Contains(searchText));
        }

        _filteredBarks = barks.ToList();

        ResultsLabel.Text = Loc.GetString($"bark-filter-founded",
            ("filtered", _filteredBarks.Count));

        BuildBarkButtons();
    }

    private void BuildBarkButtons()
    {
        BarksGrid.RemoveAllChildren();

        foreach (var bark in _filteredBarks)
        {
            var button = new Button
            {
                Text = Loc.GetString(bark.Name),
                ToggleMode = true,
                HorizontalExpand = true,
                VerticalExpand = false,
                Margin = new Thickness(2),
                Pressed = bark.ID == _currentBarkId,
            };

            button.OnPressed += _ => OnBarkButtonPressed(bark.ID);

            BarksGrid.AddChild(button);
        }
    }

    private void OnBarkButtonPressed(string barkId)
    {
        _currentBarkId = barkId;
        OnBarkSelected?.Invoke(barkId);
        UpdateBarkButtons();
        _barkSystem.PlayDataPreview(barkId, _currentPitch, _currentMinVar, _currentMaxVar);
    }

    private void UpdateBarkButtons()
    {
        foreach (var button in BarksGrid.Children.OfType<Button>())
        {
            button.Pressed = button.Text == Loc.GetString(_filteredBarks.FirstOrDefault(b => b.ID == _currentBarkId)?.Name ?? "");
        }
    }
}
