using Content.Client.UserInterface.Controls;
using Content.Shared.Speech;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Content.Shared.Utopia.CCVar;
using Content.Shared.Utopia.SpeechBarks;
using Robust.Shared.Configuration;
using System.Linq;

namespace Content.Client.VoiceMask;

[GenerateTypedNameReferences]
public sealed partial class VoiceMaskNameChangeWindow : FancyWindow
{
    public Action<string>? OnNameChange;
    public Action<string?>? OnVerbChange;
    public Action? OnToggle;
    public Action? OnAccentToggle;
    // Utopia-Tweak : Barks
    public Action<string>? OnBarkChange;
    public Action<string>? OnPitchChange;
    private List<BarkPrototype> _barks = new();
    // Utopia-Tweak : Barks
    private List<(string, string)> _verbs = new();

    private string? _verb;

    public VoiceMaskNameChangeWindow()
    {
        RobustXamlLoader.Load(this);

        NameSelectorSet.OnPressed += _ =>
        {
            OnNameChange?.Invoke(NameSelector.Text);
        };

        SpeechVerbSelector.OnItemSelected += args =>
        {
            OnVerbChange?.Invoke((string?) args.Button.GetItemMetadata(args.Id));
            SpeechVerbSelector.SelectId(args.Id);
        };

        // Utopia-Tweak : Barks
        if (IoCManager.Resolve<IConfigurationManager>().GetCVar(UCCVars.BarksEnabled))
        {
            BarksContainer.Visible = true;
            ReloadBarks(IoCManager.Resolve<IPrototypeManager>());
        }
        // Utopia-Tweak : Barks

        ToggleButton.OnPressed += args => OnToggle?.Invoke();
        ToggleAccentButton.OnPressed += args => OnAccentToggle?.Invoke();
    }

    public void ReloadVerbs(IPrototypeManager proto)
    {
        foreach (var verb in proto.EnumeratePrototypes<SpeechVerbPrototype>())
        {
            _verbs.Add((Loc.GetString(verb.Name), verb.ID));
        }
        _verbs.Sort((a, b) => a.Item1.CompareTo(b.Item1));
    }

    public void AddVerbs()
    {
        SpeechVerbSelector.Clear();

        AddVerb(Loc.GetString("chat-speech-verb-name-none"), null);
        foreach (var (name, id) in _verbs)
        {
            AddVerb(name, id);
        }
    }

    private void AddVerb(string name, string? verb)
    {
        var id = SpeechVerbSelector.ItemCount;
        SpeechVerbSelector.AddItem(name);
        if (verb is {} metadata)
            SpeechVerbSelector.SetItemMetadata(id, metadata);

        if (verb == _verb)
            SpeechVerbSelector.SelectId(id);
    }

    public void UpdateState(string name, string? verb, bool active, bool accentHide, string barkId, float barkPitch) // Utopia-Tweak : Barks
    {
        NameSelector.Text = name;
        _verb = verb;
        ToggleButton.Pressed = active;
        ToggleAccentButton.Pressed = accentHide;

        for (int id = 0; id < SpeechVerbSelector.ItemCount; id++)
        {
            if (string.Equals(verb, SpeechVerbSelector.GetItemMetadata(id)))
            {
                SpeechVerbSelector.SelectId(id);
                break;
            }
        }

        // Utopia-Tweak : Barks
        var barkIdx = _barks.FindIndex(b => b.ID == barkId);
        if (barkIdx != -1)
            BarkSelector.Select(barkIdx);
        PitchSelector.SetText(barkPitch.ToString());
        // Utopia-Tweak : Barks
    }

    // Utopia-Tweak : Barks
    private void ReloadBarks(IPrototypeManager proto)
    {
        BarkSelector.OnItemSelected += args =>
        {
            BarkSelector.SelectId(args.Id);
            if (BarkSelector.SelectedMetadata != null)
                OnBarkChange!((string)BarkSelector.SelectedMetadata);
        };
        PitchSelector.OnTextEntered += args =>
        {
            if (float.TryParse(args.Text, out var newMsg))
            {
                OnPitchChange!(args.Text);
                PitchSelector.SetText(args.Text);
            }
        };

        _barks = proto
            .EnumeratePrototypes<BarkPrototype>()
            .Where(o => o.RoundStart)
            .OrderBy(o => Loc.GetString(o.Name))
            .ToList();
        for (var i = 0; i < _barks.Count; i++)
        {
            var name = Loc.GetString(_barks[i].Name);
            BarkSelector.AddItem(name);
            BarkSelector.SetItemMetadata(i, _barks[i].ID);
        }
    }
    // Utopia-Tweak : Barks
}
