using Content.Client._Utopia.Helpers;
using Content.Client.Message;
using Content.Shared._Utopia.Economy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Utopia.Economy.UI;

[GenerateTypedNameReferences]
public sealed partial class BankUiFragment : BoxContainer
{
    public Action<BankAccountLinkMessage>? OnLinkAttempt;
    public Action<BankTransferMessage>? OnTransferAttempt;
    public Action? OnNotificationSet;

    private bool _accountLinkActive;
    private bool _transferActive;

    public BankUiFragment()
    {
        RobustXamlLoader.Load(this);


        NotificationSwitch.OnPressed += _ =>
        {
            OnNotificationSet?.Invoke();
        };

        AccountLinkButton.OnPressed += _ =>
        {
            _accountLinkActive = true;
            AccountLinkResultLabel.Visible = false;
            UpdateAccountLinkUi();
        };

        LinkCancelButton.OnPressed += _ =>
        {
            _accountLinkActive = false;
            UpdateAccountLinkUi();
        };

        PinLineEdit.OnTextChanged += _ =>
        {
            UtopiaHelper.ValidateLineEditNumbers(PinLineEdit, 4);
        };

        AccountLineEdit.OnTextChanged += _ =>
        {
            UtopiaHelper.ValidateLineEditNumbers(AccountLineEdit, 6);
        };

        LinkConfirmButton.OnPressed += _ =>
        {
            if (PinLineEdit.Text.Length != 4 || AccountLineEdit.Text.Length != 6)
                return;

            var accountId = int.Parse(AccountLineEdit.Text);
            var pin = int.Parse(PinLineEdit.Text);
            AccountLinkResultLabel.Visible = true;

            _accountLinkActive = false;
            OnLinkAttempt?.Invoke(new BankAccountLinkMessage(accountId, pin));
        };

        TransferPinLineEdit.OnTextChanged += _ =>
        {
            UtopiaHelper.ValidateLineEditNumbers(TransferPinLineEdit, 4);
        };

        TargetAccountLineEdit.OnTextChanged += _ =>
        {
            UtopiaHelper.ValidateLineEditNumbers(TargetAccountLineEdit, 6);
        };

        TransferButton.OnPressed += _ =>
        {
            _transferActive = true;
            TransferResultLabel.Visible = false;
            UpdateTransferUi();
        };

        TransferCancelButton.OnPressed += _ =>
        {
            _transferActive = false;
            UpdateTransferUi();
        };

        TransferConfirmButton.OnPressed += _ =>
        {
            if (TargetAccountLineEdit.Text.Length != 6 || TransferPinLineEdit.Text.Length != 4)
                return;

            var targetAccount = int.Parse(TargetAccountLineEdit.Text);
            var pin = int.Parse(TransferPinLineEdit.Text);

            if (!int.TryParse(TransferAmountLineEdit.Text, out var amount))
                return;

            if (amount <= 0)
                return;

            OnTransferAttempt?.Invoke(new BankTransferMessage(targetAccount, pin, amount));
            TransferResultLabel.Visible = true;

            _transferActive = false;
            UpdateTransferUi();
        };
    }

    public void UpdateState(BankCartridgeUiState state)
    {
        var accountLinked = state.AccountId != null;
        var isBlocked = state.IsBlocked;

        RichTextLabelExt.SetMarkup(AccountLinkMessageLabel, state.AccountLinkMessage);
        RichTextLabelExt.SetMarkup(AccountLinkResultLabel, state.AccountLinkResult);
        RichTextLabelExt.SetMarkup(TransferResultLabel, state.TransferResult);

        NotificationSwitch.Text = Loc.GetString(state.NotificationOn ? "news-read-ui-notification-on"
            : "news-read-ui-notification-off");

        LinkedAccount.Visible = accountLinked || !isBlocked;
        NoLinkedAccountLabel.Visible = !accountLinked || isBlocked;

        if (accountLinked && !isBlocked)
        {
            RichTextLabelExt.SetMarkup(LinkedAccountNumberLabel, Loc.GetString("bank-program-ui-account-number-text",
                ("account", state.AccountId!.Value)));
            RichTextLabelExt.SetMarkup(LinkedAccountNameLabel, Loc.GetString("bank-program-ui-account-owner-text",
                ("owner", state.OwnerName)));

            RichTextLabelExt.SetMarkup(LinkedAccountBalanceLabel, Loc.GetString("atm-ui-balance",
                ("balance", state.Balance)));

            HistoryHeader.Text = Loc.GetString("bank-program-ui-transaction-history");
            TransactionHistoryList.RemoveAllChildren();

            if (state.History.Count == 0)
            {
                var emptyLabel = new RichTextLabel();
                RichTextLabelExt.SetMarkup(emptyLabel, "[color=#888888]Нет транзакций[/color]");
                TransactionHistoryList.AddChild(emptyLabel);
            }
            else
            {
                foreach (var transaction in state.History)
                {
                    var label = new RichTextLabel();
                    var amountColor = transaction.Amount > 0 ? "#00ff00" : "#ff0000";
                    var typeText = transaction.Amount > 0 ? "+" : "";
                    RichTextLabelExt.SetMarkup(label, $"[color=#888888]{transaction.InitiatorName}[/color] [color={amountColor}]{typeText}{transaction.Amount}$[/color] - {transaction.Type} [color=#888888]({transaction.Timestamp:hh\\:mm\\:ss})[/color]");
                    TransactionHistoryList.AddChild(label);
                }
            }

            UpdateAccountLinkUi();
            UpdateTransferUi();
            return;
        }

        if (isBlocked)
        {
            RichTextLabelExt.SetMarkup(NoLinkedAccountLabel, Loc.GetString("bank-program-ui-blocked-account"));
            Stripes.Visible = false;
            return;
        }

        RichTextLabelExt.SetMarkup(NoLinkedAccountLabel, Loc.GetString("bank-program-ui-no-account"));
        UpdateAccountLinkUi();
    }

    private void UpdateAccountLinkUi()
    {
        AccountLinkButton.Visible = !_accountLinkActive;
        AccountLink.Visible = _accountLinkActive;
    }

    private void UpdateTransferUi()
    {
        TransferButton.Visible = !_transferActive;
        TransferForm.Visible = _transferActive;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        LinkConfirmButton.Disabled = PinLineEdit.Text.Length != 4 || AccountLineEdit.Text.Length != 6;
        TransferConfirmButton.Disabled = TransferPinLineEdit.Text.Length != 4 || TargetAccountLineEdit.Text.Length != 6
            || TransferAmountLineEdit.Text.Length <= 0;
    }
}
