using Content.Client.Message;
using Content.Shared._Utopia.Economy;
using Content.Shared.StationRecords;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Content.Client.UserInterface.Controls;
using Robust.Client.GameObjects;
using Robust.Shared.Prototypes;

namespace Content.Client._Utopia.Economy.UI;

[GenerateTypedNameReferences]
public sealed partial class EconomicRecordsConsoleWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;

    private readonly SpriteSystem _spriteSystem;

    public Action? OnBlockToggle;
    public Action<uint?>? OnKeySelected;
    public Action<StationRecordFilterType, string>? OnFiltersChanged;

    private bool _isPopulating;
    private StationRecordFilterType _currentFilterType;

    private static readonly HashSet<StationRecordFilterType> ExcludedFilters = new()
    {
        StationRecordFilterType.DNA,
        StationRecordFilterType.Prints,
        StationRecordFilterType.Species
    };

    public EconomicRecordsConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        _currentFilterType = StationRecordFilterType.Name;

        _spriteSystem = _entManager.System<SpriteSystem>();

        foreach (var item in Enum.GetValues<StationRecordFilterType>())
        {
            if (ExcludedFilters.Contains(item))
                continue;

            StationRecordsFilterType.AddItem(GetTypeFilterLocals(item), (int)item);
        }

        RecordListing.OnItemSelected += args =>
        {
            if (_isPopulating || RecordListing[args.ItemIndex].Metadata is not uint cast)
                return;

            OnKeySelected?.Invoke(cast);
        };

        RecordListing.OnItemDeselected += _ =>
        {
            if (!_isPopulating)
                OnKeySelected?.Invoke(null);
        };

        StationRecordsFilterType.OnItemSelected += eventArgs =>
        {
            var type = (StationRecordFilterType)eventArgs.Id;

            if (_currentFilterType != type)
            {
                _currentFilterType = type;
                FilterListingOfRecords();
            }
        };

        StationRecordsFiltersValue.OnTextEntered += args =>
        {
            FilterListingOfRecords(args.Text);
        };

        StationRecordsFiltersReset.OnPressed += _ =>
        {
            StationRecordsFiltersValue.Text = string.Empty;
            FilterListingOfRecords();
        };

        BlockAccountButton.OnToggled += _ => OnBlockToggle?.Invoke();
    }

    public void UpdateCheckBox(bool enabled)
    {
        BlockAccountButton.Pressed = enabled;
    }

    private void FilterListingOfRecords(string text = "")
    {
        if (!_isPopulating)
        {
            OnFiltersChanged?.Invoke(_currentFilterType, text);
        }
    }

    private string GetTypeFilterLocals(StationRecordFilterType type)
    {
        return Loc.GetString($"general-station-record-{type.ToString().ToLower()}-filter");
    }

    private void PopulateRecordListing(Dictionary<uint, string> listing, uint? selected)
    {
        RecordListing.Clear();
        RecordListing.ClearSelected();

        _isPopulating = true;

        foreach (var (key, name) in listing)
        {
            var item = RecordListing.AddItem(name);
            item.Metadata = key;
            item.Selected = key == selected;
        }

        _isPopulating = false;

        RecordListing.SortItemsByText();
    }

    private void PopulateRecordContainer(GeneralStationRecord stationRecord, int? accountId, int balance, List<TransactionsHistory> histories)
    {
        RecordName.Text = stationRecord.Name;
        RecordJob.Text = Loc.GetString("general-station-record-console-record-title",
            ("job", stationRecord.JobTitle));

        if (accountId != null)
        {
            AccountIdLabel.Text = Loc.GetString("bank-program-ui-account-number-text", ("account", accountId));
            BalanceLabel.Text = Loc.GetString("atm-ui-balance", ("balance", balance));
        }
        else
        {
            AccountIdLabel.Text = Loc.GetString("bank-program-ui-no-account");
        }

        HistoryHeader.Text = Loc.GetString("bank-program-ui-transaction-history");
        HistoryList.RemoveAllChildren();

        if (histories.Count == 0)
        {
            var emptyLabel = new RichTextLabel();
            RichTextLabelExt.SetMarkup(emptyLabel, "[color=#888888]Нет транзакций[/color]");
            HistoryList.AddChild(emptyLabel);
        }
        else
        {
            foreach (var transaction in histories)
            {
                var label = new RichTextLabel();
                var amountColor = transaction.Amount > 0 ? "#00ff00" : "#ff0000";
                var typeText = transaction.Amount > 0 ? "+" : "";
                RichTextLabelExt.SetMarkup(label, $"[color=#888888]{transaction.InitiatorName}[/color] [color={amountColor}]{typeText}{transaction.Amount}$[/color] - {transaction.Type} [color=#888888]({transaction.Timestamp:hh\\:mm\\:ss})[/color]");
                HistoryList.AddChild(label);
            }
        }
    }

    public void UpdateState(EconomicRecordsConsoleState state)
    {
        if (state.Filter != null)
        {
            if (state.Filter.Type != _currentFilterType)
            {
                _currentFilterType = state.Filter.Type;
            }

            if (state.Filter.Value != StationRecordsFiltersValue.Text)
            {
                StationRecordsFiltersValue.Text = state.Filter.Value;
            }
        }

        StationRecordsFilterType.SelectId((int)_currentFilterType);

        if (state.RecordListing == null)
        {
            RecordListingStatus.Visible = true;
            RecordListing.Visible = false;
            RecordListingStatus.Text = Loc.GetString("general-station-record-console-empty-state");
            RecordContainer.Visible = false;
            RecordContainerStatus.Visible = false;
            return;
        }

        RecordListingStatus.Visible = false;
        RecordListing.Visible = true;
        RecordContainer.Visible = true;

        PopulateRecordListing(state.RecordListing, state.SelectedKey);

        RecordContainerStatus.Visible = state.Record == null;

        if (state.Record != null)
        {
            RecordContainerStatus.Visible = state.SelectedKey == null;
            RecordContainerStatus.Text = state.SelectedKey == null
                ? Loc.GetString("general-station-record-console-no-record-found")
                : Loc.GetString("general-station-record-console-select-record-info");

            if (_proto.TryIndex<JobIconPrototype>(state.Record.JobIcon, out var proto))
            {
                JobIcon.Texture = _spriteSystem.Frame0(proto.Icon);
            }

            PopulateRecordContainer(state.Record, state.AccountId, state.Balance, state.History);
        }
    }
}
