using Content.Client._Utopia.Helpers;
using Content.Client.UserInterface.Controls;
using Content.Shared._Utopia.Economy;
using Content.Shared.StationRecords;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Prototypes;

namespace Content.Client._Utopia.Economy.UI;

[GenerateTypedNameReferences]
public sealed partial class SalaryConsoleMenu : FancyWindow
{
    [Dependency] private IEntityManager _entManager = default!;
    [Dependency] private IPrototypeManager _proto = default!;

    private readonly SpriteSystem _spriteSystem;

    public Action<uint?>? OnKeySelected;
    public Action<uint, int, int>? OnSendMoney;
    public Action? OnEjectCard;
    public Action<StationRecordFilterType, string>? OnFiltersChanged;

    private uint? _selectedKey;
    private StationRecordFilterType _currentFilterType;
    private bool _isPopulating;

    private static readonly HashSet<StationRecordFilterType> ExcludedFilters = new()
    {
        StationRecordFilterType.DNA,
        StationRecordFilterType.Prints,
        StationRecordFilterType.Species
    };

    public SalaryConsoleMenu()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _spriteSystem = _entManager.System<SpriteSystem>();

        _currentFilterType = StationRecordFilterType.Name;

        foreach (var item in Enum.GetValues<StationRecordFilterType>())
        {
            if (ExcludedFilters.Contains(item))
                continue;

            FilterType.AddItem(GetTypeFilterLocals(item), (int)item);
        }

        FilterType.OnItemSelected += eventArgs =>
        {
            var type = (StationRecordFilterType)eventArgs.Id;

            if (_currentFilterType != type)
            {
                _currentFilterType = type;
                FilterListingOfRecords(FilterText.Text);
            }
        };

        FilterText.OnTextEntered += args =>
        {
            FilterListingOfRecords(args.Text);
        };

        StationRecordsFiltersReset.OnPressed += _ =>
        {
            FilterText.Text = string.Empty;
            FilterListingOfRecords();
        };

        EjectCardButton.OnPressed += _ => OnEjectCard?.Invoke();
        RecordList.OnItemSelected += args =>
        {
            if (_isPopulating || RecordList[args.ItemIndex].Metadata is not uint key)
                return;

            OnKeySelected?.Invoke(key);
        };

        RecordList.OnItemDeselected += _ =>
        {
            if (!_isPopulating)
                OnKeySelected?.Invoke(null);
        };

        PinLineEdit.OnTextChanged += _ =>
        {
            UtopiaHelper.ValidateLineEditNumbers(PinLineEdit, 4);
        };

        SendButton.OnButtonDown += _ =>
        {
            if (PinLineEdit.Text.Length != 4)
                return;

            if (WithdrawSlider.Value > 0 && _selectedKey is { } key)
                OnSendMoney?.Invoke(key, WithdrawSlider.Value, int.Parse(PinLineEdit.Text));
        };
    }

    private void FilterListingOfRecords(string text = "")
    {
        if (!_isPopulating)
        {
            OnFiltersChanged?.Invoke(_currentFilterType, text);
        }
    }

    private string GetTypeFilterLocals(StationRecordFilterType type)
    {
        return Loc.GetString($"general-station-record-{type.ToString().ToLower()}-filter");
    }

    private void PopulateRecordListing(Dictionary<uint, string> listing, uint? selected)
    {
        RecordList.Clear();
        RecordList.ClearSelected();

        _isPopulating = true;

        foreach (var (key, name) in listing)
        {
            var item = RecordList.AddItem(name);
            item.Metadata = key;
            item.Selected = key == selected;
        }

        _isPopulating = false;

        RecordList.SortItemsByText();
    }

    public void UpdateState(SalaryConsoleUserInterfaceState state)
    {
        if (state.Filter != null)
        {
            if (state.Filter.Type != _currentFilterType)
            {
                _currentFilterType = state.Filter.Type;
            }

            if (state.Filter.Value != FilterText.Text)
            {
                FilterText.Text = state.Filter.Value;
            }
        }

        FilterType.SelectId((int)_currentFilterType);


        EjectCardButton.Disabled = !state.BudgetCardInserted;
        if (state.BudgetCardInserted)
        {
            PinLineEdit.Visible = true;
            WithdrawSlider.Visible = true;
            SendButton.Visible = true;

            var balance = state.BudgetCardBalance.ToString("N0") ?? "-";
            var label = state.BudgetCardLabel;
            CardLabel.Text = $"{label}: {balance}";

            WithdrawSlider.MaxValue = state.BudgetCardBalance;
            WithdrawSlider.Value = Math.Min(WithdrawSlider.Value, state.BudgetCardBalance);
        }
        else
        {
            CardLabel.Text = Loc.GetString("salary-console-no-card");
            PinLineEdit.Visible = false;
            WithdrawSlider.Visible = false;
            SendButton.Visible = false;
        }

        if (state.RecordListing == null)
        {
            RecordListStatus.Visible = true;
            RecordList.Visible = false;
            RecordListStatus.Text = Loc.GetString("general-station-record-console-empty-state");
            RecordDetailContainer.Visible = false;
            SendContainer.Visible = false;
            return;
        }

        RecordListStatus.Visible = false;
        RecordList.Visible = true;
        RecordDetailContainer.Visible = true;
        RecordPlaceholder.Visible = state.Record == null;

        _selectedKey = state.SelectedKey;
        PopulateRecordListing(state.RecordListing, _selectedKey);

        if (state.Record != null)
        {
            RecordDetailContainer.Visible = true;
            SendContainer.Visible = true;

            RecordNameLabel.Text = state.Record.Name;
            RecordJobLabel.Text = Loc.GetString("general-station-record-console-record-title",
                ("job", state.Record.JobTitle));

            if (_proto.TryIndex<JobIconPrototype>(state.Record.JobIcon, out var proto))
            {
                JobIcon.Texture = _spriteSystem.Frame0(proto.Icon);
            }

            RecordAgeLabel.Text = Loc.GetString("general-station-record-console-record-age",
                ("age", state.Record.Age.ToString()));
        }
        else
        {
            RecordDetailContainer.Visible = false;
            SendContainer.Visible = false;
        }

        SendButton.Disabled = state.BudgetCardBalance is not > 0;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        SendButton.Disabled = PinLineEdit.Text.Length != 4;
    }
}
