using Content.Client.UserInterface.Controls;
using Content.Shared._Utopia.Economy;
using Content.Shared.StationRecords;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Utopia.Economy.UI;

[GenerateTypedNameReferences]
public sealed partial class SalaryConsoleMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;

    public Action<StationRecordFilterType, string>? OnFiltersChanged;

    private readonly SpriteSystem _spriteSystem;

    private uint? _selectedKey;
    private StationRecordFilterType _currentFilterType;

    private static readonly HashSet<StationRecordFilterType> ExcludedFilters = new()
    {
        StationRecordFilterType.DNA,
        StationRecordFilterType.Prints,
        StationRecordFilterType.Species
    };

    public SalaryConsoleMenu(SalaryConsoleBoundUserInterface owner)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _spriteSystem = _entManager.System<SpriteSystem>();

        _currentFilterType = StationRecordFilterType.Name;

        foreach (var item in Enum.GetValues<StationRecordFilterType>())
        {
            if (ExcludedFilters.Contains(item))
                continue;

            FilterType.AddItem(GetTypeFilterLocals(item), (int)item);
        }

        FilterType.OnItemSelected += eventArgs =>
        {
            var type = (StationRecordFilterType)eventArgs.Id;

            if (_currentFilterType != type)
            {
                _currentFilterType = type;
                FilterListingOfRecords(FilterText.Text);
            }
        };

        FilterText.OnTextEntered += args =>
        {
            FilterListingOfRecords(args.Text);
        };

        EjectCardButton.OnPressed += _ => owner.EjectCard();
        RecordList.OnItemSelected += args =>
        {
            if (RecordList[args.ItemIndex].Metadata is not uint key)
                return;

            owner.SelectRecord(key);
        };

        RecordList.OnItemDeselected += _ => owner.SelectRecord(null);

        SendButton.OnPressed += _ =>
        {
            if (int.TryParse(AmountEdit.Text, out var amount) && amount > 0 && _selectedKey is { } key)
                owner.SendMoney(key, amount);
        };
    }

    private void FilterListingOfRecords(string text = "")
    {
        OnFiltersChanged?.Invoke(_currentFilterType, text);
    }

    private string GetTypeFilterLocals(StationRecordFilterType type)
    {
        return Loc.GetString($"criminal-records-{type.ToString().ToLower()}-filter");
    }

    public void UpdateState(SalaryConsoleUserInterfaceState state)
    {
        EjectCardButton.Disabled = !state.BudgetCardInserted;
        if (state.BudgetCardInserted)
        {
            var balance = state.BudgetCardBalance?.ToString("N0") ?? "-";
            var label = state.BudgetCardLabel ?? Loc.GetString("salary-console-budget-card");
            CardLabel.Text = $"{label}: {balance}";
        }
        else
        {
            CardLabel.Text = Loc.GetString("salary-console-no-card");
        }

        RecordList.Clear();
        if (state.RecordListing != null)
        {
            foreach (var (id, name) in state.RecordListing)
            {
                var item = RecordList.AddItem(name);
                item.Metadata = id;
            }
        }

        if (state.Record != null)
        {
            RecordPlaceholder.Visible = false;
            RecordDetailContainer.Visible = true;
            SendContainer.Visible = true;

            RecordNameLabel.Text = state.Record.Name;
            RecordJobLabel.Text = Loc.GetString("general-station-record-console-record-title",
                ("job", Loc.GetString(state.Record.JobTitle)));

            if (_proto.TryIndex<JobIconPrototype>(state.Record.JobIcon, out var proto))
            {
                JobIcon.Texture = _spriteSystem.Frame0(proto.Icon);
            }

            RecordAgeLabel.Text = Loc.GetString("general-station-record-console-record-age",
                ("age", state.Record.Age.ToString()));
        }
        else
        {
            RecordPlaceholder.Visible = true;
            RecordDetailContainer.Visible = false;
            SendContainer.Visible = false;
        }

        if (state.Filter != null)
        {
            if (state.Filter.Type != _currentFilterType)
            {
                _currentFilterType = state.Filter.Type;
            }

            if (state.Filter.Value != FilterText.Text)
            {
                FilterText.Text = state.Filter.Value;
            }
        }

        FilterType.SelectId((int)_currentFilterType);
        _selectedKey = state.SelectedKey;

        SendButton.Disabled = !state.BudgetCardInserted
            || state.SelectedKey == null
            || state.Record == null
            || state.BudgetCardBalance is not > 0;
    }
}
