using System.Numerics;
using Content.Client.Message;
using Content.Client.Resources;
using Content.Client.UserInterface.Controls;
using Content.Shared._Utopia.ModSuits;
using Content.Shared.Inventory;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;
using Robust.Shared.Timing;

namespace Content.Client._Utopia.ModSuits.UI;

[GenerateTypedNameReferences]
public sealed partial class ModSuitMenu : FancyWindow
{
    private const string PanelTexturePath = "/Textures/Interface/Nano/button.svg.96dpi.png";

    [Dependency] private IEntityManager _ent = default!;
    [Dependency] private IResourceCache _resCache = default!;

    private static readonly Color IdleModulate = Color.FromHex("#1B1B1E");
    private static readonly Color DeployedModulate = Color.FromHex("#2B3F7A");
    private static readonly Color LockedModulate = Color.FromHex("#5A2222");

    private static readonly ModSuitPart[] PartOrder =
    {
        ModSuitPart.Helmet,
        ModSuitPart.Body,
        ModSuitPart.Gloves,
        ModSuitPart.Boots,
    };

    private readonly Dictionary<ModSuitPart, PartSlot> _slots = new();
    private readonly Texture _panelTexture;

    private EntityUid? _owner;
    private EntityUid? _wearer;

    public event Action<ModSuitPart>? OnPartPressed;
    public event Action? OnToggleAllPressed;

    public ModSuitMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _panelTexture = _resCache.GetTexture(PanelTexturePath);

        if (SchematicPanel.PanelOverride is StyleBoxTexture schematicStyle)
            schematicStyle.Texture = _panelTexture;

        foreach (var part in PartOrder)
        {
            var slot = CreateSlot(part);
            _slots[part] = slot;
            PartSlots.AddChild(slot.Root);
        }

        ToggleAllButton.OnPressed += _ => OnToggleAllPressed?.Invoke();
    }

    public void SetOwner(EntityUid owner)
    {
        _owner = owner;
        RefreshWearer();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        RefreshWearer();
    }

    private void RefreshWearer()
    {
        EntityUid? wearer = null;

        if (_owner is { } owner
            && _ent.TryGetComponent<TransformComponent>(owner, out var xform)
            && xform.ParentUid.IsValid()
            && _ent.HasComponent<InventoryComponent>(xform.ParentUid))
        {
            wearer = xform.ParentUid;
        }

        if (wearer == _wearer)
            return;

        _wearer = wearer;
        WearerView.SetEntity(wearer);
        WearerView.Visible = wearer != null;
        CoreLabel.Visible = wearer == null;
    }

    private PartSlot CreateSlot(ModSuitPart part)
    {
        var style = new StyleBoxTexture
        {
            Texture = _panelTexture,
            Modulate = IdleModulate,
        };
        style.SetPatchMargin(StyleBox.Margin.All, 10);

        var icon = new TextureRect
        {
            SetSize = new Vector2(44, 44),
            Stretch = TextureRect.StretchMode.KeepAspectCentered,
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
            Visible = false,
            MouseFilter = MouseFilterMode.Ignore,
        };

        var button = new TextureButton
        {
            HorizontalExpand = true,
            VerticalExpand = true,
            ToolTip = Loc.GetString($"modsuit-ui-part-{part.ToString().ToLowerInvariant()}"),
        };
        button.AddChild(icon);
        button.OnPressed += _ => OnPartPressed?.Invoke(part);

        var root = new PanelContainer
        {
            SetSize = new Vector2(68, 68),
            PanelOverride = style,
        };
        root.AddChild(button);

        return new PartSlot(root, button, icon, style);
    }

    public void UpdateState(ModSuitBoundUiState state)
    {
        if (SchematicPanel.PanelOverride is StyleBoxTexture schematic)
            schematic.Modulate = state.Locked ? LockedModulate : state.EquippedParts > 0 ? DeployedModulate : IdleModulate;

        foreach (var (part, slot) in _slots)
        {
            if (state.Parts.TryGetValue(part, out var partState))
                UpdateSlot(slot, partState.Entity, partState.Deployed, state.Locked);
            else
                UpdateSlot(slot, null, false, state.Locked);
        }

        var statusColor = state.Status switch
        {
            ModSuitStatus.Active => Color.Lime,
            ModSuitStatus.Charging => Color.Cyan,
            ModSuitStatus.NeedCharging => Color.Yellow,
            ModSuitStatus.Dead => Color.Red,
            ModSuitStatus.SPRINGTRAPPED => Color.DarkRed,
            _ => Color.Gray,
        };
        StatusValueLabel.SetMarkup(
            $"[color={statusColor.ToHex()}]{Loc.GetString($"modsuit-ui-status-{state.Status.ToString().ToLowerInvariant()}")}[/color]");

        if (state.Charge is { } charge)
        {
            var color = charge switch
            {
                >= 0.5f => Color.Lime,
                >= 0.25f => Color.Yellow,
                _ => Color.Red,
            };

            ChargeBar.Visible = true;
            ChargeBar.Value = charge;
            ChargeValueLabel.SetMarkup(
                $"[color={color.ToHex()}]{Loc.GetString("modsuit-ui-charge-value", ("percent", (charge * 100).ToString("F0")))}[/color]");
        }
        else
        {
            ChargeBar.Visible = false;
            ChargeValueLabel.SetMarkup(Loc.GetString("modsuit-ui-no-battery"));
        }

        PartsValueLabel.SetMarkup(Loc.GetString("modsuit-ui-parts-value",
            ("equipped", state.EquippedParts),
            ("total", state.TotalParts)));

        TotalDrawValueLabel.SetMarkup(Loc.GetString("modsuit-ui-watt-value", ("watt", state.TotalDraw.ToString("F1"))));
        BaseDrawValueLabel.SetMarkup(Loc.GetString("modsuit-ui-watt-value", ("watt", state.BaseDraw.ToString("F1"))));

        var currentPartsDraw = state.EquippedParts * state.DrawPerPart;
        PartsDrawValueLabel.SetMarkup(Loc.GetString("modsuit-ui-parts-draw-value",
            ("perPart", state.DrawPerPart.ToString("F1")),
            ("total", currentPartsDraw.ToString("F1"))));

        ModulesDrawValueLabel.SetMarkup(Loc.GetString("modsuit-ui-watt-value", ("watt", state.ModulesDraw.ToString("F1"))));

        LockedLabel.Visible = state.Locked;
        if (state.Locked)
            LockedLabel.Text = Loc.GetString("modsuit-ui-locked");

        ToggleAllButton.Text = state.EquippedParts == 0
            ? Loc.GetString("modsuit-ui-toggle-all-deploy")
            : Loc.GetString("modsuit-ui-toggle-all-retract");
        ToggleAllButton.Disabled = state.Locked && state.EquippedParts == 0;

        ModulesContainer.RemoveAllChildren();
        NoModulesLabel.Visible = state.Modules.Count == 0;

        foreach (var module in state.Modules)
            ModulesContainer.AddChild(CreateModuleEntry(module));
    }

    private void UpdateSlot(PartSlot slot, NetEntity? entity, bool deployed, bool locked)
    {
        Texture? texture = null;

        if (entity is { } netEnt && _ent.TryGetEntity(netEnt, out var uid) && uid is { } partUid)
        {
            texture = GetItemIcon(partUid);
            slot.Button.Modulate = Color.White;
        }
        else
        {
            slot.Button.Modulate = Color.FromHex("#808080");
        }

        slot.Icon.Texture = texture;
        slot.Icon.Visible = texture != null;

        slot.Style.Modulate = deployed ? DeployedModulate : locked ? LockedModulate : IdleModulate;
    }

    private Control CreateModuleEntry(ModSuitModuleUiState module)
    {
        var icon = new TextureRect
        {
            SetSize = new Vector2(32, 32),
            Stretch = TextureRect.StretchMode.KeepAspectCentered,
            VerticalAlignment = VAlignment.Center,
        };

        if (_ent.TryGetEntity(module.Entity, out var uid) && uid is { } moduleUid)
            icon.Texture = GetItemIcon(moduleUid);

        var nameLabel = new Label
        {
            Text = module.Name,
            VerticalAlignment = VAlignment.Center,
            HorizontalExpand = true,
            ClipText = true,
        };

        var powerLabel = new Label
        {
            Text = module.Active
                ? Loc.GetString("modsuit-ui-watt-value", ("watt", module.Expenditure.ToString("F1")))
                : Loc.GetString("modsuit-ui-module-off"),
            StyleClasses = { module.Active ? "LabelSubText" : "LabelDisabled" },
            VerticalAlignment = VAlignment.Center,
            HorizontalAlignment = HAlignment.Right
        };

        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(4),
            SeparationOverride = 6,
        };
        row.AddChild(icon);
        row.AddChild(nameLabel);
        row.AddChild(powerLabel);

        var style = new StyleBoxTexture
        {
            Texture = _panelTexture,
            Modulate = module.Active ? IdleModulate : LockedModulate,
        };
        style.SetPatchMargin(StyleBox.Margin.All, 10);

        var panel = new PanelContainer { PanelOverride = style };
        panel.AddChild(row);
        return panel;
    }

    private Texture? GetItemIcon(EntityUid uid)
    {
        var sprites = _ent.System<SpriteSystem>();

        if (_ent.TryGetComponent<IconComponent>(uid, out var icon))
            return sprites.GetIcon(icon);

        if (_ent.TryGetComponent<SpriteComponent>(uid, out var sprite))
            return sprite.Icon?.Default;

        if (_ent.TryGetComponent<MetaDataComponent>(uid, out var meta)
            && meta.EntityPrototype is { } proto)
            return sprites.Frame0(proto);

        return null;
    }

    private sealed record PartSlot(
        PanelContainer Root,
        TextureButton Button,
        TextureRect Icon,
        StyleBoxTexture Style);
}
