using Content.Client.UserInterface.Controls;
using Content.Shared._Utopia.ZLevels.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Utopia.ZLevels.Ladders;

[GenerateTypedNameReferences]
public sealed partial class ZLevelLadderMenu : RadialMenu
{
    private EntityUid _owner;

    [Dependency] private IEntityManager _entMan = default!;
    [Dependency] private IResourceCache _resCache = default!;

    public event Action<ZMoveDirection>? OnSelected;

    public ZLevelLadderMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void SetEntity(EntityUid uid)
    {
        _owner = uid;
    }

    public void UpdateMenu(List<ZMoveDirection> directions)
    {
        Main.RemoveAllChildren();

        var rsiPath = new ResPath("/Textures/_Utopia/Structures/ladders.rsi");
        if (_entMan.TryGetComponent<SpriteComponent>(_owner, out var spriteComp) && spriteComp.BaseRSI != null)
        {
            rsiPath = spriteComp.BaseRSI.Path;
        }

        var rsi = _resCache.GetResource<RSIResource>(rsiPath).RSI;

        foreach (var dir in directions)
        {
            var localDir = dir;
            var isUp = localDir == ZMoveDirection.Up;
            var overlayState = isUp ? "up" : "down";

            var button = new RadialMenuButtonWithSector
            {
                ToolTip = isUp ? "Up" : "Down"
            };

            var baseTex = new TextureRect
            {
                Texture = rsi["icon"].Frame0,
                Stretch = TextureRect.StretchMode.KeepCentered
            };
            var overlayTex = new TextureRect
            {
                Texture = rsi[overlayState].Frame0,
                Stretch = TextureRect.StretchMode.KeepCentered
            };

            button.AddChild(baseTex);
            button.AddChild(overlayTex);

            button.OnPressed += _ => OnSelected?.Invoke(localDir);

            Main.AddChild(button);
        }
    }
}
