using Content.Shared._Utopia.Supermatter;
using Content.Shared._Utopia.Supermatter.Components;
using Content.Shared.Atmos;
using Content.Shared.Atmos.EntitySystems;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Utopia.Supermatter.Consoles;

[GenerateTypedNameReferences]
public sealed partial class SupermatterConsoleMenu : FancyWindow
{
    public event Action<NetEntity?>? OnEntrySelected;

    private readonly Dictionary<int, NetEntity> _rowToEntity = new();
    private readonly IEntityManager _entMan;
    private readonly SharedAtmosphereSystem _atmosphere;

    private bool _isUpdating;

    public SupermatterConsoleMenu()
    {
        RobustXamlLoader.Load(this);

        _entMan = IoCManager.Resolve<IEntityManager>();
        _atmosphere = _entMan.System<SharedAtmosphereSystem>();

        SupermatterList.OnItemSelected += args =>
        {
            if (_isUpdating)
                return;

            if (_rowToEntity.TryGetValue(args.ItemIndex, out var netEntity))
                OnEntrySelected?.Invoke(netEntity);
        };

        SupermatterList.OnItemDeselected += _ =>
        {
            if (_isUpdating)
                return;

            OnEntrySelected?.Invoke(null);
        };
    }

    public void UpdateState(SupermatterConsoleBoundInterfaceState state)
    {
        if (Disposed)
            return;

        UpdateList(state.Supermatters, state.FocusData?.NetEntity);
        UpdateFocus(state.FocusData);
    }

    private void UpdateList(SupermatterConsoleEntry[] entries, NetEntity? focused)
    {
        _isUpdating = true;

        SupermatterList.Clear();
        _rowToEntity.Clear();

        for (var i = 0; i < entries.Length; i++)
        {
            var entry = entries[i];
            var status = Loc.GetString(GetStatusLoc(entry.Status));
            var item = SupermatterList.AddItem($"{entry.Location} — {entry.Integrity:F0}% ({status})");
            item.Selected = focused != null && entry.NetEntity == focused.Value;
            _rowToEntity[i] = entry.NetEntity;
        }

        _isUpdating = false;
    }

    private void UpdateFocus(SupermatterFocusData? data)
    {
        if (Disposed)
            return;

        var hasFocus = data != null;

        InfoContainer.Visible = hasFocus;
        StatsScroll.Visible = hasFocus;
        NoneSelectedLabel.Visible = !hasFocus;

        GasScrollContainer.Visible = hasFocus;
        GasNoneSelectedLabel.Visible = !hasFocus;

        SpritePlaceholderLabel.Visible = !hasFocus;
        SmSprite.Visible = false;
        SmPrototypeView.Visible = false;

        if (data == null)
        {
            SmSprite.SetEntity(null);
            SmPrototypeView.SetPrototype(null);
            if (!GasContainer.Disposed)
                GasContainer.DisposeAllChildren();
            return;
        }

        if (_entMan.TryGetEntity(data.NetEntity, out var uid))
        {
            SmSprite.SetEntity(uid.Value);
            SmSprite.Visible = true;
            SmPrototypeView.SetPrototype(null);
        }
        else if (!string.IsNullOrEmpty(data.Prototype))
        {
            SmSprite.SetEntity(null);
            SmPrototypeView.SetPrototype(data.Prototype);
            SmPrototypeView.Visible = true;
        }
        else
        {
            SpritePlaceholderLabel.Visible = true;
        }

        NameValueLabel.SetMessage(FormattedMessage.FromMarkupPermissive(data.EntityName));

        var integrityColor = GetIntegrityColor(data.Integrity);
        StatusValueLabel.SetMessage(FormattedMessage.FromMarkupOrThrow($"[color={integrityColor.ToHex()}]{Loc.GetString(GetStatusLoc(data.Status))}[/color]"));

        UpdateIntegrityBar(data.Integrity, integrityColor);
        UpdateTemperatureBar(data);
        MaxTemperatureValueLabel.SetMessage(FormattedMessage.FromMarkupOrThrow($"{data.MaxTemperature:F1} K"));
        MinTemperatureValueLabel.SetMessage(FormattedMessage.FromMarkupOrThrow($"{data.MinTemperature:F1} K"));
        TotalEnergyValueLabel.SetMessage(FormattedMessage.FromMarkupOrThrow($"{data.TotalEnergy:F0} КэВ"));
        InternalEnergyValueLabel.SetMessage(FormattedMessage.FromMarkupOrThrow($"{data.InternalEnergy:F0} КэВ"));
        ExternalEnergyValueLabel.SetMessage(FormattedMessage.FromMarkupOrThrow($"{data.ExternalEnergy:F0} КэВ"));
        RadiationValueLabel.SetMessage(FormattedMessage.FromMarkupOrThrow($"{data.Radiation:F2} Рад"));

        UpdateGasList(data.GasStorage);
        UpdateModifiers(data);
    }

    private void UpdateModifiers(SupermatterFocusData data)
    {
        EnergyScaleModifierValueLabel.SetMessage(
            FormattedMessage.FromMarkupOrThrow($"x{data.EnergyScaleModifier:F2}"));
        EnergyReductionModifierValueLabel.SetMessage(
            FormattedMessage.FromMarkupOrThrow($"x{data.EnergyReductionModifier:F2}"));
        TemperatureScaleModifierValueLabel.SetMessage(
            FormattedMessage.FromMarkupOrThrow($"x{data.TemperatureScaleModifier:F2}"));
        WasteOutputModifierLabel.SetMessage(
            FormattedMessage.FromMarkupOrThrow($"x{data.WasteOutputModifier:F2}"));
        TemperatureProtectionModifierValueLabel.SetMessage(
            FormattedMessage.FromMarkupOrThrow($"x{data.TemperatureProtectionModifier:F2}"));
    }

    private void UpdateGasList(GasMixture mixture)
    {
        if (Disposed || GasContainer.Disposed)
            return;

        GasContainer.DisposeAllChildren();

        var total = mixture.TotalMoles;

        for (var i = 0; i < Atmospherics.TotalNumberOfGases; i++)
        {
            var moles = mixture.GetMoles(i);
            if (moles <= 0.01f)
                continue;

            var percent = total > 0f ? moles / total * 100f : 0f;
            var gasProto = _atmosphere.GetGas(i);
            var gasName = Loc.GetString(gasProto.Name);

            GasContainer.AddChild(CreateGasRow(gasName, moles, percent, gasProto.Color));
        }

        if (GasContainer.ChildCount == 0)
        {
            GasContainer.AddChild(new Label
            {
                Text = Loc.GetString("supermatter-console-gas-empty"),
                HorizontalAlignment = HAlignment.Center,
            });
        }
    }

    private void UpdateIntegrityBar(float integrity, Color color)
    {
        IntegrityBar.MinValue = 0f;
        IntegrityBar.MaxValue = 100f;
        IntegrityBar.Value = integrity;
        IntegrityBarLabel.Text = Loc.GetString("supermatter-console-window-label-integrity-bar",
            ("integrity", $"{integrity:F1}"));
        SetBarColor(IntegrityBar, color);
    }

    private void UpdateTemperatureBar(SupermatterFocusData data)
    {
        var temperature = data.Temperature;
        var minLimit = data.MinTemperature;
        var maxLimit = data.MaxTemperature;
        var range = Math.Max(maxLimit - minLimit, 1f);

        var barMin = Math.Min(minLimit - range * 0.25f, temperature);
        var barMax = Math.Max(maxLimit + range * 0.25f, temperature);

        TemperatureBar.MinValue = barMin;
        TemperatureBar.MaxValue = barMax;
        TemperatureBar.Value = temperature;
        TemperatureBarLabel.Text = Loc.GetString("supermatter-console-window-label-temperature-bar",
            ("temperature", $"{temperature:F1}"));

        Color color;
        if (temperature > maxLimit)
            color = Color.Red;
        else if (temperature < minLimit)
            color = Color.Cyan;
        else
            color = Color.Lime;

        SetBarColor(TemperatureBar, color);
    }

    private static void SetBarColor(ProgressBar bar, Color color)
    {
        bar.ForegroundStyleBoxOverride ??= new StyleBoxFlat();
        ((StyleBoxFlat) bar.ForegroundStyleBoxOverride).BackgroundColor = color;
    }

    private static Control CreateGasRow(string gasName, float moles, float percent, Color barColor)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 8),
        };

        var header = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };

        header.AddChild(new Label
        {
            Text = gasName,
            HorizontalExpand = true,
        });
        header.AddChild(new Label
        {
            Text = $"{percent:F1}% ({moles:F1} mol)",
            HorizontalAlignment = HAlignment.Right,
        });

        var bar = new ProgressBar
        {
            MinValue = 0,
            MaxValue = 100,
            Value = percent,
            MinHeight = 16,
            HorizontalExpand = true,
            ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = barColor },
        };

        row.AddChild(header);
        row.AddChild(bar);

        return row;
    }

    private static string GetStatusLoc(SupermatterStatus status)
    {
        return status switch
        {
            SupermatterStatus.Inactive => "supermatter-console-window-status-inactive",
            SupermatterStatus.Stable => "supermatter-console-window-status-normal",
            SupermatterStatus.Warning => "supermatter-console-window-status-warning",
            SupermatterStatus.Destabilization => "supermatter-console-window-status-danger",
            SupermatterStatus.Catastrophe => "supermatter-console-window-status-emergency",
            SupermatterStatus.Delamination => "supermatter-console-window-status-delaminating",
            _ => "supermatter-console-window-status-error",
        };
    }

    private static Color GetIntegrityColor(float integrity)
    {
        return integrity switch
        {
            >= 75f => Color.Lime,
            >= 50f => Color.Yellow,
            >= 25f => Color.Orange,
            _ => Color.Red,
        };
    }
}
