using System.Linq;
using System.Numerics;
using Content.Client._Utopia.Research.UI;
using Content.Client.Parallax;
using Content.Client.UserInterface.Controls;
using Content.Shared.Access.Components;
using Content.Shared.Access.Systems;
using Content.Shared._Utopia.Research;
using Content.Shared.Research.Components;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class ResearchConsoleMenu : FancyWindow
{
    public Action<string>? OnTechnologyCardPressed;
    public Action? OnServerButtonPressed;
    public Action<ProtoId<TechDisciplinePrototype>>? OnDisciplineButtonPressed;

    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IPlayerManager _player = default!;

    private readonly ResearchSystem _research;
    private readonly SpriteSystem _sprite;
    private readonly AccessReaderSystem _accessReader;
    private ParallaxControl _parallaxControl;

    public string ParallaxPrototype { get; set; } = "Default";
    public void SetParallaxPrototype(string parallaxPrototype)
    {
        ParallaxPrototype = parallaxPrototype;
        _parallaxControl?.ParallaxPrototype = parallaxPrototype;
    }

    public EntityUid Entity;
    public ProtoId<TechDisciplinePrototype> CurrentDiscipline;
    public ProtoId<TechnologyPrototype>? CurrentTech;
    public Dictionary<string, ResearchAvailablity> List = new();
    private ResearchConsoleBoundInterfaceState _localState = new(0, new(), new());
    private Vector2 _position = new Vector2(45, 250);
    private bool _draggin;

    private readonly Dictionary<ProtoId<TechDisciplinePrototype>, DisciplineButton> _disciplineButtons = new();
    private IReadOnlyList<TechDisciplinePrototype> _sortedDisciplines = Array.Empty<TechDisciplinePrototype>();

    public ResearchConsoleMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _research = _entity.System<ResearchSystem>();
        _sprite = _entity.System<SpriteSystem>();
        _accessReader = _entity.System<AccessReaderSystem>();

        _parallaxControl = new ParallaxControl
        {
            ParallaxPrototype = ParallaxPrototype,
            HorizontalExpand = true,
            VerticalExpand = true,
        };

        ResearchesContainer.AddChild(_parallaxControl);

        _parallaxControl.SetPositionInParent(0);

        ServerButton.OnPressed += _ => OnServerButtonPressed?.Invoke();
        DragContainer.OnKeyBindDown += OnKeybindDown;
        DragContainer.OnKeyBindUp += OnKeybindUp;
        RecenterButton.OnPressed += _ => Recenter();

        UpdatePanels(_localState);
    }

    public void SetEntity(EntityUid entity)
    {
        Entity = entity;
    }

    public void UpdatePanels(ResearchConsoleBoundInterfaceState state)
    {
        List = state.Researches;
        _localState = state;

        EnsureDisciplineButtons();

        if (state.CurrentDiscipline != CurrentDiscipline)
        {
            CurrentDiscipline = state.CurrentDiscipline;
        }

        foreach (var (disciplineId, button) in _disciplineButtons)
        {
            var pressed = disciplineId == CurrentDiscipline;
            button.SetClickPressed(pressed);

            if (pressed)
            {
                _parallaxControl.ModulateSelfOverride = button.Proto.Color;
            }
        }

        DragContainer.DisposeAllChildren();

        foreach (var tech in _prototype.EnumeratePrototypes<TechnologyPrototype>().Where(x => x.Discipline == CurrentDiscipline))
        {
            if (!List.ContainsKey(tech.ID))
                continue;

            var control = new ResearchConsoleItem(tech, _sprite, List[tech.ID]);
            DragContainer.AddChild(control);

            LayoutContainer.SetPosition(control, _position + tech.Position * 150);
            control.SelectAction += SelectTech;

            if (tech.ID == CurrentTech)
            {
                SelectTech(tech, List[tech.ID]);
            }
        }
    }

    private void EnsureDisciplineButtons()
    {
        if (_disciplineButtons.Count > 0)
            return;

        _sortedDisciplines = _prototype.EnumeratePrototypes<TechDisciplinePrototype>()
            .OrderBy(x => x.Name)
            .ToList();

        foreach (var proto in _sortedDisciplines)
        {
            var discipline = new DisciplineButton(proto)
            {
                ToggleMode = true,
                HorizontalExpand = true,
                VerticalExpand = true,
                MuteSounds = true,
                Text = Loc.GetString(proto.Name),
                Margin = new(2)
            };

            discipline.OnPressed += SelectDiscipline;
            _disciplineButtons[proto.ID] = discipline;
            DisciplinesContainer.AddChild(discipline);
        }
    }

    public void UpdateInformationPanel(ResearchConsoleBoundInterfaceState state)
    {
        var amountMsg = new FormattedMessage();
        amountMsg.AddMarkupOrThrow(Loc.GetString("research-console-menu-research-points-text", ("points", state.Points)));
        ResearchAmountLabel.SetMessage(amountMsg);

        if (!_entity.TryGetComponent(Entity, out TechnologyDatabaseComponent? database))
            return;

        TierDisplayContainer.DisposeAllChildren();
        foreach (var disciplineId in database.SupportedDisciplines)
        {
            var discipline = _prototype.Index(disciplineId);
            var percentage = _research.GetHighestDisciplineTier(database, discipline);

            var texture = new TextureRect
            {
                TextureScale = new Vector2(2, 2),
                VerticalAlignment = VAlignment.Center
            };

            var label = new RichTextLabel();
            texture.Texture = _sprite.Frame0(discipline.Icon);
            label.SetMessage(Loc.GetString("research-console-tier-percentage", ("perc", percentage)));

            var control = new BoxContainer
            {
                Children =
                {
                    texture,
                    label,
                    new Control
                    {
                        MinWidth = 10
                    }
                }
            };

            TierDisplayContainer.AddChild(control);
        }
    }

    #region Drag handle
    protected override void MouseMove(GUIMouseMoveEventArgs args)
    {
        base.MouseMove(args);

        if (!_draggin)
            return;

        _position += args.Relative;

        foreach (var child in DragContainer.Children)
        {
            LayoutContainer.SetPosition(child, child.Position + args.Relative);
        }
    }

    private void OnKeybindDown(GUIBoundKeyEventArgs args)
    {
        if (args.Function == EngineKeyFunctions.Use)
            _draggin = true;
    }

    private void OnKeybindUp(GUIBoundKeyEventArgs args)
    {
        if (args.Function == EngineKeyFunctions.Use)
            _draggin = false;
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        return _draggin ? DragMode.None : base.GetDragModeFor(relativeMousePos);
    }

    #endregion

    public void SelectTech(TechnologyPrototype proto, ResearchAvailablity avaibility)
    {
        InfoContainer.DisposeAllChildren();
        if (!_player.LocalEntity.HasValue)
            return;

        CurrentTech = proto.ID;
        var control = new TechnologyInfoPanel(proto, _sprite, _accessReader.IsAllowed(_player.LocalEntity.Value, Entity), avaibility);
        control.BuyAction += args => OnTechnologyCardPressed?.Invoke(args.ID);
        InfoContainer.AddChild(control);
    }

    public void SelectDiscipline(BaseButton.ButtonEventArgs args)
    {
        if (args.Button is not DisciplineButton discipline)
            return;

        var proto = discipline.Proto;
        CurrentDiscipline = proto.ID;

        discipline.SetClickPressed(false);
        OnDisciplineButtonPressed?.Invoke(proto.ID);

        UpdatePanels(_localState);
    }

    public void Recenter()
    {
        _position = new(45, 250);
        foreach (var item in DragContainer.Children)
        {
            if (item is not ResearchConsoleItem research)
                continue;

            LayoutContainer.SetPosition(item, _position + research.Prototype.Position * 150);
        }
    }

    public override void Close()
    {
        base.Close();

        DragContainer.RemoveAllChildren();
        InfoContainer.RemoveAllChildren();
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        InfoContainer.DisposeAllChildren();
        foreach (var item in DisciplinesContainer.Children)
        {
            if (item is not DisciplineButton button)
                continue;

            button.OnPressed -= SelectDiscipline;
        }
    }

    private sealed partial class DisciplineButton(TechDisciplinePrototype proto) : Button
    {
        public TechDisciplinePrototype Proto = proto;
    }
}

