using Content.Client.DoAfter;
using Content.Client.UserInterface.Controls;
using Content.Shared.Power.Generator;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;

namespace Content.Client.Power.Generator;

[GenerateTypedNameReferences]
public sealed partial class GeneratorWindow : FancyWindow
{
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private ILocalizationManager _loc = default!;

    private EntityUid _entity;
    private PortableGeneratorComponentBuiState? _lastState; // Utopia-Tweak : PACMAN-updt

    public event Action<int>? OnPower;
    public event Action<bool>? OnState;
    public event Action? OnSwitchOutput;
    public event Action? OnEjectFuel;

    public GeneratorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // Utopia-Tweak : PACMAN-updt
        TargetPowerSlider.OnValueChanged += _ => UpdatePowerPreview();
        TargetPowerSlider.OnReleased += _ => OnPower?.Invoke((int) TargetPowerSlider.Value);
        // Utopia-Tweak : PACMAN-updt

        StartButton.OnPressed += _ => OnState?.Invoke(true);
        StopButton.OnPressed += _ => OnState?.Invoke(false);
        OutputSwitchButton.OnPressed += _ => OnSwitchOutput?.Invoke();
        FuelEject.OnPressed += _ => OnEjectFuel?.Invoke();
    }

    public void SetEntity(EntityUid entity)
    {
        _entity = entity;
        EntityView.SetEntity(entity);
    }

    public void Update(PortableGeneratorComponentBuiState state)
    {
        _lastState = state; // Utopia-Tweak : PACMAN-updt

        if (!_entityManager.TryGetComponent(_entity, out FuelGeneratorComponent? component))
            return;

        // Utopia-Tweak : PACMAN-updt
        TargetPowerSlider.MinValue = component.MinTargetPower / 1000f;
        TargetPowerSlider.MaxValue = state.MaximumPower / 1000f;

        if (!TargetPowerSlider.Grabbed)
            TargetPowerSlider.SetValueWithoutEvent(state.TargetPower / 1000f);

        UpdatePowerPreview(state, component);
        // Utopia-Tweak : PACMAN-updt

        var progress = 0f;

        var unanchored = !_entityManager.GetComponent<TransformComponent>(_entity).Anchored;
        var starting = !unanchored && TryGetStartProgress(out progress);
        var on = !unanchored && !starting && state.On;
        var off = !unanchored && !starting && !state.On;

        LabelUnanchored.Visible = unanchored;
        StartProgress.Visible = starting;
        StopButton.Visible = on;
        StartButton.Visible = off;

        if (starting)
        {
            StatusLabel.Text = _loc.GetString("portable-generator-ui-status-starting");
            StatusLabel.SetOnlyStyleClass("negative");

            StartProgress.Value = progress;
        }
        else if (on)
        {
            StatusLabel.Text = _loc.GetString("portable-generator-ui-status-running");
            StatusLabel.SetOnlyStyleClass("positive");
        }
        else
        {
            StatusLabel.Text = _loc.GetString("portable-generator-ui-status-stopped");
            StatusLabel.SetOnlyStyleClass("highlight");
        }

        var canSwitch = _entityManager.TryGetComponent(_entity, out PowerSwitchableComponent? switchable);
        var switcher = _entityManager.System<SharedPowerSwitchableSystem>();
        OutputSwitchLabel.Visible = canSwitch;
        OutputSwitchButton.Visible = canSwitch;

        if (switchable != null)
        {
            var voltage = switcher.VoltageString(switcher.GetVoltage(_entity, switchable));
            OutputSwitchLabel.Text = Loc.GetString("portable-generator-ui-current-output", ("voltage", voltage));
            var nextVoltage = switcher.VoltageString(switcher.GetNextVoltage(_entity, switchable));
            OutputSwitchButton.Text = Loc.GetString("power-switchable-switch-voltage", ("voltage", nextVoltage));
            OutputSwitchButton.Disabled = state.On;
        }

        CloggedLabel.Visible = state.Clogged;

        // Utopia-Tweak : PACMAN-updt
        var hasTemperature = state.TemperatureCelsius.HasValue;
        TemperatureLabel.Visible = hasTemperature;
        TemperatureContainer.Visible = hasTemperature;

        if (state.TemperatureCelsius is { } temperature)
        {
            const float criticalTemperature = 150f;

            TemperatureBar.MaxValue = criticalTemperature;
            TemperatureBar.Value = Math.Clamp(temperature, 0f, criticalTemperature);

            TemperatureValue.Text = Loc.GetString(
                "portable-generator-ui-temperature-value",
                ("temperature", (int) MathF.Round(temperature)));

            var critical = temperature >= criticalTemperature;
            var warning = temperature >= 100f;

            TemperatureBar.SetOnlyStyleClass(
                critical
                    ? "negative"
                    : warning
                        ? "highlight"
                        : "positive");
        }
        // Utopia-Tweak : PACMAN-updt

        if (state.NetworkStats is { } netStats)
        {
            NetworkStats.Text = Loc.GetString(
                "portable-generator-ui-network-stats-value",
                ("load", netStats.Load),
                ("supply", netStats.Supply));

            var good = netStats.Load <= netStats.Supply;
            NetworkStats.SetOnlyStyleClass(good ? "positive" : "highlight");
        }
        else
        {
            NetworkStats.Text = Loc.GetString("portable-generator-ui-network-stats-not-connected");
            NetworkStats.StyleClasses.Clear();
        }
    }

    // Utopia-Tweak : PACMAN-updt
    private void UpdatePowerPreview()
    {
        if (!_entityManager.TryGetComponent(_entity, out FuelGeneratorComponent? component))
            return;

        UpdatePowerPreview(_lastState, component);
    }

    private void UpdatePowerPreview(PortableGeneratorComponentBuiState? state, FuelGeneratorComponent component)
    {
        var targetPowerKw = (int) TargetPowerSlider.Value;
        TargetPowerLabel.Text = targetPowerKw.ToString();

        var targetPower = targetPowerKw * 1000f;
        var optimalPower = state?.OptimalPower ?? component.OptimalPower;
        var efficiency = SharedGeneratorSystem.CalcFuelEfficiency(targetPower, optimalPower, component);
        Efficiency.Text = efficiency.ToString("P1");

        if (state == null)
            return;

        var burnRate = component.OptimalBurnRate / efficiency;
        var left = state.RemainingFuel / burnRate;

        Eta.Text = Loc.GetString(
            "portable-generator-ui-eta",
            ("minutes", Math.Ceiling(left / 60.0)));
        FuelFraction.Value = state.RemainingFuel - (int) state.RemainingFuel;
        FuelLeft.Text = ((int) MathF.Floor(state.RemainingFuel)).ToString();
    }
    // Utopia-Tweak : PACMAN-updt

    private bool TryGetStartProgress(out float progress)
    {
        // Try to check progress of auto-revving first
        if (_entityManager.TryGetComponent<ActiveGeneratorRevvingComponent>(_entity, out var activeGeneratorRevvingComponent) && _entityManager.TryGetComponent<PortableGeneratorComponent>(_entity, out var portableGeneratorComponent))
        {
            var calculatedProgress = activeGeneratorRevvingComponent.CurrentTime / portableGeneratorComponent.StartTime;
            progress = (float) calculatedProgress;
            return true;
        }

        var doAfterSystem = _entityManager.EntitySysManager.GetEntitySystem<DoAfterSystem>();
        return doAfterSystem.TryFindActiveDoAfter<GeneratorStartedEvent>(_entity, out _, out _, out progress);
    }
}
