using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._Utopia.Telescience.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Utopia.Telescience.UI;

[GenerateTypedNameReferences]
public sealed partial class TelescienceWindow : FancyWindow
{
    [Dependency] private readonly IGameTiming _timing = default!;
    [Dependency] private readonly IEntityManager _ent = default!;

    private TelescienceState _state;

    private Entity<TelescienceComputerComponent>? _computer;

    public event Action<Vector2>? OnSendButtonPressed;
    public event Action<Vector2>? OnRetrieveButtonPressed;
    public event Action<Vector2>? OnPositionChange;
    public event Action<Vector2>? OnOpenPortalButtonPressed;
    public event Action? OnClosePortalButtonPressed;

    public TelescienceWindow(EntityUid owner, TelescienceComputerComponent computer)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _computer = (owner, computer);

        SendButton.OnPressed += _ =>
        {
            OnSendButtonPressed?.Invoke(new Vector2(XNodeInput.Value, YNodeInput.Value));
        };

        RetrieveButton.OnPressed += _ =>
        {
            OnRetrieveButtonPressed?.Invoke(new Vector2(XNodeInput.Value, YNodeInput.Value));
        };

        PortalButton.OnPressed += _ =>
        {
            OnOpenPortalButtonPressed?.Invoke(new Vector2(XNodeInput.Value, YNodeInput.Value));
        };

        XNodeInput.OnValueChanged += _ =>
        {
            OnPositionChange?.Invoke(new Vector2(XNodeInput.Value, YNodeInput.Value));
        };

        YNodeInput.OnValueChanged += _ =>
        {
            OnPositionChange?.Invoke(new Vector2(XNodeInput.Value, YNodeInput.Value));
        };

        ClosePortalButton.OnPressed += _ => OnClosePortalButtonPressed?.Invoke();

        Update((owner, computer));
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        if (_computer == null)
            return;

        UpdateState();
        UpdateButton();
        UpdateStatusText();
        CooldownProgressBar();
    }

    private void Update(Entity<TelescienceComputerComponent> ent)
    {
        UpdateState();
        UpdateButton();
        UpdateStatusText();
        SetCoordinates(ent);
    }

    private void UpdateState()
    {
        if (_computer == null)
            return;

        _state = TelescienceState.Unknown;

        if (_computer.Value.Comp.TeleporterUid == null)
        {
            _state = TelescienceState.NotConnected;
        }
        else
        {
            _state = TelescienceState.Ready;
        }

        if (_computer.Value.Comp.CooldownTime > _timing.CurTime)
        {
            _state = TelescienceState.Cooldown;
        }
    }

    private void UpdateButton()
    {
        switch (_state)
        {
            case TelescienceState.NotConnected:
            case TelescienceState.Cooldown:
                PortalButton.Disabled = true;
                ClosePortalButton.Disabled = true;
                SendButton.Disabled = true;
                RetrieveButton.Disabled = true;
                break;
            case TelescienceState.Ready:
                PortalButton.Disabled = false;
                ClosePortalButton.Disabled = false;
                SendButton.Disabled = false;
                RetrieveButton.Disabled = false;
                break;
        }
    }

    private void UpdateStatusText()
    {
        var output = Loc.GetString("teleporter-computer-status-unknown");
        switch (_state)
        {
            case TelescienceState.Ready:
                output = Loc.GetString("teleporter-computer-status-ready");
                break;
            case TelescienceState.NotConnected:
                output = Loc.GetString("teleporter-computer-status-not-connected");
                break;
            case TelescienceState.Cooldown:
                output = Loc.GetString("teleporter-computer-status-cooldown");
                break;
        }

        StatusOutput.Text = output;
    }

    private void SetCoordinates(Entity<TelescienceComputerComponent> ent)
    {
        XNodeInput.Value = ent.Comp.Position.X;
        YNodeInput.Value = ent.Comp.Position.Y;
    }

    private enum TelescienceState
    {
        Unknown,
        NotConnected,
        Ready,
        Cooldown,
    }

    private void CooldownProgressBar()
    {
        if (_computer == null || _state <= TelescienceState.NotConnected)
        {
            ChargeBar.Value = 0;
            ChargeBarText.Text = "0%";
            return;
        }

        if (_state == TelescienceState.Cooldown)
        {
            var (_, computer) = _computer.Value;

            if (computer.TeleporterUid == null
            || !_ent.TryGetComponent<TelescienceTeleporterComponent>(computer.TeleporterUid, out var teleporter))
                return;

            var progress = 1 - (computer.CooldownTime - _timing.CurTime) / teleporter.CooldownInterval;

            ChargeBar.Value = (float)progress;
            ChargeBarText.Text = $"{progress:P0}";
            return;
        }

        ChargeBar.Value = 1;
        ChargeBarText.Text = "100%";
    }
}
