using Content.Shared._Utopia.Research;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Utopia.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class ResearchConsoleItem : LayoutContainer
{
    public TechnologyPrototype Prototype;
    public Action<TechnologyPrototype, ResearchAvailablity>? SelectAction;
    public ResearchAvailablity Availablity;

    public ResearchConsoleItem(TechnologyPrototype proto, SpriteSystem sprite, ResearchAvailablity availablity)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        Availablity = availablity;
        Prototype = proto;

        ResearchDisplay.Texture = sprite.Frame0(proto.Icon);
        Panel.Button.OnPressed += Selected;
        (Panel.Color, Panel.HoveredColor, Panel.BorderColor) = availablity switch
        {
            ResearchAvailablity.Researched => (Color.DarkOliveGreen, Color.PaleGreen, Color.LimeGreen),
            ResearchAvailablity.Available => (Color.FromHex("#1297a3"), Color.FromHex("#1ee8fa"), Color.DarkCyan),
            ResearchAvailablity.Unavailable => (Color.DarkRed, Color.FromHex("#ad1111"), Color.Crimson),
            _ => (Color.DarkRed, Color.PaleVioletRed, Color.Crimson)
        };
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        Panel.Button.OnPressed -= Selected;
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        Panel.Button.OnPressed -= Selected;
    }

    private void Selected(BaseButton.ButtonEventArgs args)
    {
        SelectAction?.Invoke(Prototype, Availablity);
    }
}
