using Content.Client.Research;
using Content.Client.Research.UI;
using Content.Client.Lathe;
using Content.Shared._Utopia.Research;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Utopia.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class TechnologyInfoPanel : Control
{
    [Dependency] private readonly IEntityManager _ent = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;
    private readonly LatheSystem _lathe;

    public TechnologyPrototype Prototype;
    public Action<TechnologyPrototype>? BuyAction;
    public TechnologyInfoPanel(TechnologyPrototype proto, SpriteSystem sprite, bool hasAccess, ResearchAvailablity availablity)
    {
        RobustXamlLoader.Load(this);

        IoCManager.InjectDependencies(this);
        Prototype = proto;

        _lathe = _ent.System<LatheSystem>();
        var research = _ent.System<ResearchSystem>();

        TechnologyNameLabel.Text = Loc.GetString(proto.Name);
        DisciplineTexture.Texture = sprite.Frame0(_proto.Index(proto.Discipline).Icon);
        TechnologyTexture.Texture = sprite.Frame0(proto.Icon);

        NoPrereqLabel.Visible = proto.TechnologyPrerequisites.Count == 0;
        PrereqsContainer.Visible = !NoPrereqLabel.Visible;

        RequiredTechContainer.RemoveAllChildren();
        foreach (var techId in proto.TechnologyPrerequisites)
        {
            var tech = _proto.Index(techId);
            var description = research.GetTechnologyDescription(tech, true, false, true);
            RequiredTechContainer.AddChild(new MiniTechnologyCardControl(tech, _proto, sprite, description));
        }

        UnlocksContainer.DisposeAllChildren();
        foreach (var item in proto.RecipeUnlocks)
        {
            var recipe = _proto.Index(item);
            var control = new MiniRecipeCardControl(proto, recipe, _proto, sprite, _lathe);
            UnlocksContainer.AddChild(control);
        }

        if (!hasAccess)
            ResearchButton.ToolTip = Loc.GetString("research-console-no-access-popup");

        Color? color = null;
        switch (availablity)
        {
            case ResearchAvailablity.Researched:
                {
                    ResearchButton.Text = Loc.GetString("research-console-menu-server-researched-button");
                    color = Color.LimeGreen;
                    break;
                }
            case ResearchAvailablity.Unavailable:
                {
                    color = Color.Crimson;
                    break;
                }
            case ResearchAvailablity.Available:
                break;
        }

        TechnologyCostLabel.SetMessage(Loc.GetString("research-console-tech-cost-label",
            ("cost", proto.Cost)), defaultColor: color);

        ResearchButton.Disabled = !hasAccess || availablity != ResearchAvailablity.Available;
        ResearchButton.OnPressed += Bought;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        ResearchButton.OnPressed -= Bought;
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        ResearchButton.OnPressed -= Bought;
    }

    private void Bought(BaseButton.ButtonEventArgs args)
    {
        BuyAction?.Invoke(Prototype);
    }
}
