using Content.Client.UserInterface.Controls;
using Content.Shared._Utopia.Toxicology;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Utopia.Toxicology.UI;

[GenerateTypedNameReferences]
public sealed partial class ExplosionBeaconConsoleWindow : FancyWindow
{
    public ExplosionBeaconConsoleWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(ExplosionBeaconConsoleState state)
    {
        if (!state.Linked)
        {
            StatusLabel.Text = Loc.GetString("explosion-beacon-console-not-linked");
            TargetSlopeLabel.Text = ":";
            TargetIntensityLabel.Text = ":";
            TargetCurrentIntensityLabel.Text = ":";
            AttemptsLabel.Text = ":";
            LastSlopeLabel.Text = ":";
            LastIntensityLabel.Text = ":";
            LastCurrentIntensityLabel.Text = ":";
            LastPointsLabel.Text = ":";
            return;
        }

        StatusLabel.Text = Loc.GetString("explosion-beacon-console-linked");
        TargetSlopeLabel.Text = state.TargetSlope.ToString("F1");
        TargetIntensityLabel.Text = state.TargetIntensity.ToString("F1");
        TargetCurrentIntensityLabel.Text = state.TargetCurrentIntensity.ToString("F1");
        AttemptsLabel.Text = Loc.GetString(
            "explosion-beacon-console-attempts-value",
            ("current", state.CurrentAttempt),
            ("max", state.MaxAttempts));

        LastSlopeLabel.Text = FormatOptional(state.LastSlope);
        LastIntensityLabel.Text = FormatOptional(state.LastTotalIntensity);
        LastCurrentIntensityLabel.Text = FormatOptional(state.LastCurrentIntensity);
        LastPointsLabel.Text = state.LastPoints?.ToString() ?? ":";
    }

    private static string FormatOptional(float? value) =>
        value.HasValue ? value.Value.ToString("F1") : ":";
}
