using System;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._Utopia.Toxicology;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.ResourceManagement;
using System.Collections.Generic;
using System.IO;
using Robust.Shared.ContentPack;
using Robust.Shared.Utility;

namespace Content.Client._Utopia.Toxicology.UI;

[GenerateTypedNameReferences]
public sealed partial class ExplosionBeaconConsoleWindow : FancyWindow
{
    [Dependency] private readonly IResourceCache _resourceCache = default!;
    private static readonly Color SubText = new(0.62f, 0.65f, 0.70f);

    public ExplosionBeaconConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var rsi = _resourceCache.GetResource<RSIResource>(
            new ResPath("/Textures/Structures/Machines/rndpointsource.rsi")).RSI;

        if (rsi.TryGetState("rndpointsource-icon", out var state))
            BeaconSprite.Texture = state.Frame0;

        TitleLabel.FontColorOverride = Color.White;
        TitleLabel.StyleClasses.Add(StyleNano.StyleClassLabelHeading);

        TargetHeaderLabel.FontColorOverride = Color.White;
        LastHeaderLabel.FontColorOverride = Color.White;

        TargetIntensityLabel.FontColorOverride = SubText;
        TargetCurrentIntensityLabel.FontColorOverride = SubText;
        AttemptsLabel.FontColorOverride = SubText;

        LastIntensityLabel.FontColorOverride = SubText;
        LastCurrentIntensityLabel.FontColorOverride = SubText;
        LastPointsLabel.FontColorOverride = SubText;

        Title = Loc.GetString("explosion-beacon-console-window-title");
        TitleLabel.Text = Loc.GetString("explosion-beacon-console-window-header-title");
        TargetHeaderLabel.Text = Loc.GetString("explosion-beacon-console-target-header");
        LastHeaderLabel.Text = Loc.GetString("explosion-beacon-console-last-header");

        TargetIntensityLabel.Text = Loc.GetString("explosion-beacon-console-target-intensity");
        TargetCurrentIntensityLabel.Text = Loc.GetString("explosion-beacon-console-target-current-intensity");
        AttemptsLabel.Text = Loc.GetString("explosion-beacon-console-attempts-header");

        LastIntensityLabel.Text = Loc.GetString("explosion-beacon-console-last-intensity");
        LastCurrentIntensityLabel.Text = Loc.GetString("explosion-beacon-console-last-current-intensity");
        LastPointsLabel.Text = Loc.GetString("explosion-beacon-console-last-points");
    }

    public void UpdateState(ExplosionBeaconConsoleState state)
    {
        BeaconSprite.Modulate = state.Linked ? Color.White : Color.FromHex("#555555");

        SetStatusBadge(state.Linked);

        var none = Loc.GetString("explosion-beacon-console-no-data");

        if (!state.Linked)
        {
            TargetIntensityValueLabel.Text = none;
            TargetCurrentIntensityValueLabel.Text = none;

            AttemptsValueLabel.Text = none;
            AttemptsValueLabel.FontColorOverride = Color.White;
            AttemptsBar.Value = 0;
            SetAttemptsBorderColor(new Color(0.17f, 0.19f, 0.22f));

            LastIntensityValueLabel.Text = none;
            LastCurrentIntensityValueLabel.Text = none;
            LastPointsValueLabel.Text = none;
            return;
        }

        TargetIntensityValueLabel.Text = state.TargetIntensity.ToString("F1");
        TargetCurrentIntensityValueLabel.Text = state.TargetCurrentIntensity.ToString("F1");

        AttemptsValueLabel.Text = Loc.GetString(
            "explosion-beacon-console-attempts-value",
            ("current", state.CurrentAttempt),
            ("max", state.MaxAttempts));
        AttemptsValueLabel.FontColorOverride = state.CurrentAttempt >= state.MaxAttempts
            ? new Color(0.85f, 0.2f, 0.2f)
            : Color.White;

        AttemptsBar.MaxValue = MathF.Max(state.MaxAttempts, 1);
        AttemptsBar.Value = state.CurrentAttempt;
        SetAttemptsBorderColor(AttemptsColor(state.CurrentAttempt, state.MaxAttempts));

        LastIntensityValueLabel.Text = FormatOptional(state.LastTotalIntensity, none);
        LastCurrentIntensityValueLabel.Text = FormatOptional(state.LastCurrentIntensity, none);
        LastPointsValueLabel.Text = state.LastPoints.HasValue ? state.LastPoints.Value.ToString() : none;
    }

    private void SetStatusBadge(bool linked)
    {
        var background = linked ? new Color(0.13f, 0.42f, 0.20f) : new Color(0.55f, 0.10f, 0.10f);
        var text = linked
            ? Loc.GetString("explosion-beacon-console-linked")
            : Loc.GetString("explosion-beacon-console-not-linked");

        StatusBadge.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = background,
            ContentMarginLeftOverride = 10,
            ContentMarginRightOverride = 10,
            ContentMarginTopOverride = 3,
            ContentMarginBottomOverride = 3,
        };

        StatusLabel.Text = text;
        StatusLabel.FontColorOverride = Color.White;
    }

    private void SetAttemptsBorderColor(Color color)
    {
        AttemptsBorder.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = new Color(0.07f, 0.08f, 0.10f),
            BorderColor = color,
            BorderThickness = new Thickness(2),
        };
    }

    private static Color AttemptsColor(int current, int max)
    {
        if (max <= 0)
            return new Color(0.2f, 0.75f, 0.3f);

        var ratio = (float)current / max;
        return ratio switch
        {
            >= 1f => new Color(0.7f, 0.1f, 0.1f),
            > 0.65f => new Color(0.85f, 0.55f, 0.1f),
            _ => new Color(0.2f, 0.75f, 0.3f),
        };
    }

    private static string FormatOptional(float? value, string none) =>
        value.HasValue ? value.Value.ToString("F1") : none;
}
