using Content.Shared._Utopia.Language;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Utopia.Language.UI;

[GenerateTypedNameReferences]
public sealed partial class LanguageEntry : Control
{
    public Action<string>? OnLanguageSelected;
    public string Language;

    public LanguageEntry(LanguagePrototype proto, bool translator)
    {
        RobustXamlLoader.Load(this);

        NameLabel.Text = proto.LocalizedName;
        Description.SetMessage(proto.LocalizedDescription);
        Language = proto.ID;

        var uiColor = proto.UiColor;

        if (uiColor.HasValue)
        {
            NameLabel.FontColorOverride = uiColor.Value;
        }

        SelectButton.ToolTip = translator
            ? Loc.GetString("language-choose-button-tooltip-translator")
            : Loc.GetString("language-choose-button-tooltip-known");

        SelectButton.OnPressed += _ => OnLanguageSelected?.Invoke(proto.ID);
    }

}
