using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Utopia.Language;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Utopia.Language.UI;

[GenerateTypedNameReferences]
public sealed partial class LanguageMenuWindow : FancyWindow
{
    private readonly SharedLanguageSystem _language;
    private readonly IPrototypeManager _proto;

    private readonly Dictionary<string, LanguageEntry> _entries = new();
    public EntityUid Owner = EntityUid.Invalid;

    public Action<string>? OnLanguageSelected;

    public LanguageMenuWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _language = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<LanguageSystem>();
        _proto = IoCManager.Resolve<IPrototypeManager>();

        Title = Loc.GetString("language-menu-window-title");
    }

    public void UpdateState(string current, Dictionary<string, LanguageKnowledge> options, Dictionary<string, LanguageKnowledge> translator)
    {
        var currentProto = _language.GetLanguage(current);
        CurrentLanguageLabel.Text = Loc.GetString(
            "language-menu-current-language",
            ("language", currentProto.LocalizedName)
        );

        RemoveObsoleteEntries(options, translator);
        FilterTranslatorOverlaps(options, translator);

        if (options.Count > 0)
        {
            var sortedOptions = SortLanguageOptions(options, translator);
            AddLanguageEntries(sortedOptions, translator);
        }

        UpdateEntryButtonStates(current);
    }

    private void RemoveObsoleteEntries(Dictionary<string, LanguageKnowledge> options, Dictionary<string, LanguageKnowledge> translator)
    {
        var entriesToRemove = _entries.Values
            .Where(entry => !options.ContainsKey(entry.Language) && !translator.ContainsKey(entry.Language))
            .ToList();

        foreach (var entry in entriesToRemove)
        {
            OptionsList.RemoveChild(entry);
            _entries.Remove(entry.Language);
        }
    }

    private void FilterTranslatorOverlaps(Dictionary<string, LanguageKnowledge> options, Dictionary<string, LanguageKnowledge> translator)
    {
        foreach (var item in translator.ToList())
        {
            if (options.TryGetValue(item.Key, out var value) && value >= translator[item.Key])
            {
                translator.Remove(item.Key);
            }
        }
    }

    private List<KeyValuePair<string, LanguageKnowledge>> SortLanguageOptions(Dictionary<string, LanguageKnowledge> options, Dictionary<string, LanguageKnowledge> translator)
    {
        var list = options.ToList();

        list.Sort((x, y) => _proto.Index<LanguagePrototype>(x.Key).LocalizedName[0]
            .CompareTo(_proto.Index<LanguagePrototype>(y.Key).LocalizedName[0]));

        list.Sort((x, y) => _proto.Index<LanguagePrototype>(y.Key).Priority
            .CompareTo(_proto.Index<LanguagePrototype>(x.Key).Priority));

        list.Sort((x, y) => _language.CanSpeak(Owner, y.Key)
            .CompareTo(_language.CanSpeak(Owner, x.Key)));

        list.Sort((x, y) => translator.ContainsKey(x.Key)
            .CompareTo(translator.ContainsKey(y.Key)));

        return list;
    }

    private void AddLanguageEntries(List<KeyValuePair<string, LanguageKnowledge>> languages, Dictionary<string, LanguageKnowledge> translator)
    {
        foreach (var language in languages)
        {
            AddLanguageEntry(language.Key, translator.ContainsKey(language.Key));
        }
    }

    private void AddLanguageEntry(string language, bool translator = false)
    {
        if (_entries.ContainsKey(language))
            return;

        var prototype = _language.GetLanguage(language);
        var entry = new LanguageEntry(prototype, translator);

        entry.OnLanguageSelected += args => OnLanguageSelected?.Invoke(args);

        OptionsList.AddChild(entry);
        _entries.Add(language, entry);
    }

    private void UpdateEntryButtonStates(string currentLanguage)
    {
        foreach (var entry in _entries.Values)
        {
            var isCurrent = entry.Language == currentLanguage;
            var canSpeak = _language.CanSpeak(Owner, _language.GetLanguage(entry.Language));

            entry.SelectButton.Disabled = isCurrent || !canSpeak;

            if (entry.Language == currentLanguage)
            {
                entry.SelectButton.Text = Loc.GetString("language-choose-button-chosen");
            }

            else if (!canSpeak)
            {
                entry.SelectButton.Text = Loc.GetString("language-choose-button-cannot");
            }
        }
    }
}
