using System;
using Content.Client.UserInterface.Controls;
using Content.Shared._Utopia.ZLevels.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Utopia.ZLevels.Ladders;

[GenerateTypedNameReferences]
public sealed partial class ZLevelLadderMenu : RadialMenu
{
    [Dependency] private readonly IEntityManager _entMan = default!;

    public event Action<ZMoveDirection>? OnSelected;

    public ZLevelLadderMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void SetEntity(EntityUid uid)
    {
        if (!_entMan.TryGetComponent(uid, out ZLevelLadderComponent? comp))
            return;

        Main.RemoveAllChildren();

        foreach (var dir in comp.Directions)
        {
            var localDir = dir;

            var button = new RadialMenuButtonWithSector
            {
                ToolTip = localDir == ZMoveDirection.Up ? "Up" : "Down"
            };

            button.OnPressed += _ => OnSelected?.Invoke(localDir);

            Main.AddChild(button);
        }
    }
}