using System;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Power.Turbines.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Power.Turbines;

public sealed partial class TurbineConsoleWindow : FancyWindow
{
    private ItemList _turbineList = default!;
    private Label _focusName = default!;
    private Label _currentRpm = default!;
    private Label _maxRpm = default!;
    private Label _maxTemp = default!;
    private ProgressBar _integrityBar = default!;
    private Label _integrityLabel = default!;
    private PanelContainer _integrityBorder = default!;

    public event Action<NetEntity?>? OnTurbineSelected;

    public TurbineConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        _turbineList = this.FindControl<ItemList>("TurbineList");
        _focusName = this.FindControl<Label>("FocusName");
        _currentRpm = this.FindControl<Label>("CurrentRpmLabel");
        _maxRpm = this.FindControl<Label>("MaxRpmLabel");
        _maxTemp = this.FindControl<Label>("MaxTempLabel");
        _integrityBar = this.FindControl<ProgressBar>("IntegrityBar");
        _integrityLabel = this.FindControl<Label>("IntegrityLabel");
        _integrityBorder = this.FindControl<PanelContainer>("IntegrityBorder");

        _turbineList.OnItemSelected += args =>
        {
            if (args.ItemList[args.ItemIndex].Metadata is NetEntity turbine)
                OnTurbineSelected?.Invoke(turbine);
        };
    }

    public void UpdateState(TurbineConsoleBoundInterfaceState state)
    {
        UpdateList(state);
        UpdateFocus(state.FocusData);
    }

    private void UpdateList(TurbineConsoleBoundInterfaceState state)
    {
        _turbineList.Clear();

        foreach (var entry in state.Turbines)
        {
            var item = _turbineList.AddItem(entry.EntityName);
            item.Metadata = entry.NetEntity;
        }
    }

    private void UpdateFocus(TurbineFocusData? focus)
    {
        if (focus == null)
        {
            _focusName.Text = "No turbine selected";
            _currentRpm.Text = "-";
            _maxRpm.Text = "-";
            _maxTemp.Text = "-";
            _integrityBar.Value = 0;
            _integrityLabel.Text = "";
            return;
        }

        _focusName.Text = $"Turbine {focus.Value.NetEntity}";
        _currentRpm.Text = $"{focus.Value.CurrentRPM:0}";
        _maxRpm.Text = $"{focus.Value.MaxRPM:0}";
        _maxTemp.Text = $"{focus.Value.MaxTemperature:0} K";

        _integrityBar.Value = focus.Value.Integrity;
        _integrityLabel.Text = $"{focus.Value.Integrity:0}%";
    }
}
