using System;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Power.Turbines.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Power.Turbines;

public sealed partial class TurbineConsoleWindow : FancyWindow
{
    private ItemList _turbineList = default!;
    private Label _titleLabel = default!;
    private Label _turbinesHeaderLabel = default!;
    private Label _rpmLabel = default!;
    private Label _pressureLabel = default!;
    private Label _tempLabel = default!;
    private Label _integrityLabel = default!;
    private Label _focusName = default!;
    private PanelContainer _statusBadge = default!;
    private Label _statusLabel = default!;
    private Label _rpmValue = default!;
    private Label _pressureValue = default!;
    private Label _tempValue = default!;
    private PanelContainer _integrityBorder = default!;
    private ProgressBar _integrityBar = default!;
    private Label _integrityPercent = default!;
    private Label _energyLabel = default!;
    private Label _energyValue = default!;
    private Button _toggleActiveButton = default!;
    private TextureRect _turbineSprite = default!;

    private bool _currentFocusActive;
    private NetEntity? _currentFocusEntity;

    public event Action<NetEntity?>? OnTurbineSelected;
    public event Action<NetEntity, bool>? OnTurbineToggled;

    public TurbineConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        _turbineList = this.FindControl<ItemList>("TurbineList");
        _titleLabel = this.FindControl<Label>("TitleLabel");
        _turbinesHeaderLabel = this.FindControl<Label>("TurbinesHeaderLabel");
        _rpmLabel = this.FindControl<Label>("RpmLabel");
        _pressureLabel = this.FindControl<Label>("PressureLabel");
        _tempLabel = this.FindControl<Label>("TempLabel");
        _integrityLabel = this.FindControl<Label>("IntegrityLabel");
        _focusName = this.FindControl<Label>("FocusName");
        _statusBadge = this.FindControl<PanelContainer>("StatusBadge");
        _statusLabel = this.FindControl<Label>("StatusLabel");
        _rpmValue = this.FindControl<Label>("RpmValueLabel");
        _pressureValue = this.FindControl<Label>("PressureValueLabel");
        _tempValue = this.FindControl<Label>("TempValueLabel");
        _integrityBorder = this.FindControl<PanelContainer>("IntegrityBorder");
        _integrityBar = this.FindControl<ProgressBar>("IntegrityBar");
        _integrityPercent = this.FindControl<Label>("IntegrityPercentLabel");
        _energyLabel = this.FindControl<Label>("EnergyLabel");
        _energyValue = this.FindControl<Label>("EnergyValueLabel");
        _toggleActiveButton = this.FindControl<Button>("ToggleActiveButton");
        _turbineSprite = this.FindControl<TextureRect>("TurbineSprite");

        _turbineList.OnItemSelected += args =>
        {
            if (args.ItemList[args.ItemIndex].Metadata is NetEntity turbine)
                OnTurbineSelected?.Invoke(turbine);
        };

        _toggleActiveButton.OnPressed += _ =>
        {
            if (_currentFocusEntity != null)
                OnTurbineToggled?.Invoke(_currentFocusEntity.Value, !_currentFocusActive);
        };

        var accent = new Color(0.60f, 0.82f, 1.00f);
        var subText = new Color(0.62f, 0.65f, 0.70f);

        _titleLabel.FontColorOverride = Color.White;
        _titleLabel.StyleClasses.Add(StyleNano.StyleClassLabelHeading);

        _focusName.FontColorOverride = subText;
        _turbinesHeaderLabel.FontColorOverride = Color.White;

        _rpmLabel.FontColorOverride = subText;
        _pressureLabel.FontColorOverride = subText;
        _tempLabel.FontColorOverride = subText;
        _integrityLabel.FontColorOverride = subText;
        _energyLabel.FontColorOverride = subText;

        Title = Loc.GetString("turbine-console-window-title");
        _titleLabel.Text = Loc.GetString("turbine-console-window-header-title");
        _turbinesHeaderLabel.Text = Loc.GetString("turbine-console-window-header-turbines");
        _rpmLabel.Text = Loc.GetString("turbine-console-window-label-rpm");
        _pressureLabel.Text = Loc.GetString("turbine-console-window-label-pressure");
        _tempLabel.Text = Loc.GetString("turbine-console-window-label-temp");
        _integrityLabel.Text = Loc.GetString("turbine-console-window-label-integrity");
        _energyLabel.Text = Loc.GetString("turbine-console-window-label-energy");
        
        _toggleActiveButton.Text = "---";
        _toggleActiveButton.Disabled = true;
    }

    public void UpdateState(TurbineConsoleBoundInterfaceState state)
    {
        UpdateList(state);
        UpdateFocus(state.FocusData);
    }

    private void UpdateList(TurbineConsoleBoundInterfaceState state)
    {
        _turbineList.Clear();

        foreach (var entry in state.Turbines)
        {
            var item = _turbineList.AddItem($"[{StatusTag(entry.Status)}] {entry.EntityName}");
            item.Metadata = entry.NetEntity;
        }
    }

    private void UpdateFocus(TurbineFocusData? focus)
    {
        if (focus == null)
        {
            _currentFocusEntity = null;
            _currentFocusActive = false;

            _focusName.Text = Loc.GetString("turbine-console-window-no-turbine-selected");
            SetStatusBadge(null);

            _toggleActiveButton.Disabled = true;
            _toggleActiveButton.Text = "---";

            var none = Loc.GetString("turbine-console-window-value-none");
            _rpmValue.Text = none;
            _pressureValue.Text = none;
            _tempValue.Text = none;
            _energyValue.Text = none;

            _integrityBar.Value = 0;
            _integrityPercent.Text = none;
            SetIntegrityBorderColor(new Color(0.17f, 0.19f, 0.22f));

            _turbineSprite.Modulate = Color.FromHex("#555555");
            return;
        }

        var data = focus.Value;
        _currentFocusEntity = data.NetEntity;
        _currentFocusActive = data.IsActive;

        _focusName.Text = Loc.GetString("turbine-console-window-turbine-name", ("netEntity", data.NetEntity));
        SetStatusBadge(data.Status);

        _toggleActiveButton.Disabled = false;
        _toggleActiveButton.Text = _currentFocusActive 
            ? Loc.GetString("turbine-console-window-button-disable") 
            : Loc.GetString("turbine-console-window-button-enable");

        _rpmValue.Text = Loc.GetString("turbine-console-window-value-rpm", 
            ("current", data.CurrentRPM.ToString("0")), 
            ("max", data.MaxRPM.ToString("0")));

        _pressureValue.Text = Loc.GetString("turbine-console-window-value-pressure", 
            ("current", data.CurrentPressure.ToString("0")), 
            ("max", data.MaxPressure.ToString("0")));

        _tempValue.Text = Loc.GetString("turbine-console-window-value-temp", 
            ("current", data.CurrentTemperature.ToString("0")), 
            ("max", data.MaxTemperature.ToString("0")));

        _energyValue.Text = Loc.GetString("turbine-console-window-value-energy", 
            ("energy", data.Energy.ToString("0")));
            
        _integrityBar.Value = data.Integrity;
        _integrityPercent.Text = Loc.GetString("turbine-console-window-value-integrity", 
            ("integrity", data.Integrity.ToString("0")));
            
        SetIntegrityBorderColor(IntegrityColor(data.Integrity));

        _turbineSprite.Modulate = _currentFocusActive ? Color.White : Color.FromHex("#555555");
    }

    private void SetStatusBadge(TurbineStatusType? status)
    {
        var (background, text) = status switch
        {
            null => (new Color(0.20f, 0.21f, 0.24f), "-"),
            TurbineStatusType.Off => (new Color(0.24f, 0.25f, 0.27f), Loc.GetString("turbine-console-window-status-off")),
            TurbineStatusType.Nominal => (new Color(0.13f, 0.42f, 0.20f), Loc.GetString("turbine-console-window-status-nominal")),
            TurbineStatusType.Warning => (new Color(0.55f, 0.36f, 0.05f), Loc.GetString("turbine-console-window-status-warning")),
            TurbineStatusType.Critical => (new Color(0.55f, 0.10f, 0.10f), Loc.GetString("turbine-console-window-status-critical")),
            _ => (new Color(0.24f, 0.25f, 0.27f), "-"),
        };

        _statusBadge.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = background,
            ContentMarginLeftOverride = 10,
            ContentMarginRightOverride = 10,
            ContentMarginTopOverride = 3,
            ContentMarginBottomOverride = 3,
        };

        _statusLabel.Text = text;
        _statusLabel.FontColorOverride = Color.White;
    }

    private void SetIntegrityBorderColor(Color color)
    {
        _integrityBorder.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = new Color(0.07f, 0.08f, 0.10f),
            BorderColor = color,
            BorderThickness = new Thickness(2),
        };
    }

    private static Color IntegrityColor(float integrity)
    {
        return integrity switch
        {
            <= 0f => new Color(0.7f, 0.1f, 0.1f),
            < 35f => new Color(0.85f, 0.2f, 0.2f),
            < 70f => new Color(0.85f, 0.55f, 0.1f),
            _ => new Color(0.2f, 0.75f, 0.3f),
        };
    }

    private static string StatusTag(TurbineStatusType status)
    {
        return status switch
        {
            TurbineStatusType.Off => Loc.GetString("turbine-console-window-tag-off"),
            TurbineStatusType.Nominal => Loc.GetString("turbine-console-window-tag-nominal"),
            TurbineStatusType.Warning => Loc.GetString("turbine-console-window-tag-warning"),
            TurbineStatusType.Critical => Loc.GetString("turbine-console-window-tag-critical"),
            _ => "?",
        };
    }
}
