using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Utopia.UserInterface.Controls;

[GenerateTypedNameReferences]
public sealed partial class PanelButton : Button
{
    public event Action? OnDrawModeChanged;

    public PanelButton()
    {
        RobustXamlLoader.Load(this);
        MouseFilter = MouseFilterMode.Stop;
    }

    protected override void DrawModeChanged()
    {
        OnDrawModeChanged?.Invoke();
    }
}
