using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Utopia.UserInterface.Controls;

[GenerateTypedNameReferences]
public sealed partial class PanelButton : Button
{
    public event Action? OnDrawModeChanged;

    public PanelButton()
    {
        RobustXamlLoader.Load(this);
        MouseFilter = MouseFilterMode.Stop;

        TextLabel.Visible = false;
        TextLabel.ReservesSpace = false;
    }

    public new string? Text
    {
        get => TextLabel.Text;
        set => TextLabel.Text = value;
    }

    protected override void DrawModeChanged()
    {
        OnDrawModeChanged?.Invoke();
    }
}
